function renderRoute(){state.route=getRoute();renderNav();const renderers={dashboard:renderDashboard,resources:renderResources,curriculum:renderCurriculum,generator:renderGenerator,editor:renderEditor,'my-plans':renderMyPlans,sources:renderSources,settings:renderSettings,legal:renderSources};(renderers[state.route]||renderDashboard)();}

function renderDashboard(){
  const recent=[...state.plans].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).slice(0,4);
  const body=`<div class="hero"><span class="eyebrow">教師備課工作台</span><h1>今天想備哪一堂課？</h1><p>從班級需求開始，建立、校訂並保存一份真正能帶進教室的教案。</p><div class="hero-actions"><button class="btn btn-teal" data-go="generator">建立教案</button><button class="btn btn-hero-secondary" data-go="chatgpt-app" data-chatgpt-app>使用 ChatGPT 共備</button></div></div>
  <div class="dashboard-grid"><section class="card card-body dashboard-recent"><div class="section-heading"><div><h2>最近教案</h2><p>${state.plans.length} 份教案・${state.session?'雲端同步':'本機保存'}</p></div>${state.plans.length?'<button class="btn btn-secondary btn-sm" data-go="my-plans">查看全部</button>':''}</div><div class="recent-plan-list">${recent.length?recent.map(p=>`<button class="recent-plan" data-open-plan="${p.id}"><span><strong>${escapeHtml(p.title)}</strong><small>${escapeHtml(p.subject)}・${p.grade||'未設定'}年級</small></span><time>${formatDate(p.updatedAt)}</time></button>`).join(''):'<div class="empty compact"><p>尚未建立教案。</p><button class="btn btn-primary" data-go="generator">建立第一份教案</button></div>'}</div></section>
  <aside class="teacher-check"><strong>上課前請核對</strong><p>課綱、來源、授權、多語內容與活動安全仍由教師做最終判斷。</p><button class="text-link" data-go="curriculum">檢視課綱與來源 →</button></aside></div>`;
  setMain(`<section class="page">${body}</section>`);bindGoButtons();document.querySelectorAll('[data-open-plan]').forEach(b=>b.addEventListener('click',()=>{setCurrentPlan(b.dataset.openPlan);navigate('editor')}));
}
function bindGoButtons(){document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.go)));}

function renderResources(){
  const body=`<div id="resource-notice" class="notice">正在讀取資源狀態…</div><div class="card filter-bar"><div class="filter-grid"><input id="resource-q" maxlength="80" placeholder="搜尋關鍵字" value="${escapeHtml(state.resourceQuery)}"><select id="resource-subject"><option value="">全部科目</option>${SUBJECTS.map(s=>`<option>${s}</option>`).join('')}</select><select id="resource-grade"><option value="">全部年級</option>${[1,2,3,4,5,6].map(g=>`<option value="${g}">${g}年級</option>`).join('')}</select><select id="resource-language"><option value="">全部語言</option>${LANGUAGES.map(s=>`<option>${s}</option>`).join('')}</select><select id="resource-issue"><option value="">全部議題</option>${ISSUES.map(s=>`<option>${s}</option>`).join('')}</select></div><div class="header-actions" style="margin-top:12px"><button id="resource-search" class="btn btn-primary">搜尋</button><button id="resource-reset" class="btn btn-secondary">清除</button></div></div><div id="resource-results" class="resource-list">${Array.from({length:6},()=>'<div class="skeleton"></div>').join('')}</div>`;
  setMain(pageShell('教育資源資料庫','正式 API 可用時透過伺服器代理教育大市集；未設定或失敗時自動切換 EduCraft 示範資料。',body,'<button id="show-favorites" class="btn btn-secondary">只看收藏</button>'));
  document.querySelector('#resource-search').addEventListener('click',()=>loadResources());document.querySelector('#resource-reset').addEventListener('click',()=>{state.resourceQuery='';document.querySelectorAll('.filter-grid input,.filter-grid select').forEach(el=>el.value='');loadResources();});document.querySelector('#show-favorites').addEventListener('click',()=>renderResourceCards(state.favorites,true));document.querySelector('#resource-q').addEventListener('keydown',e=>{if(e.key==='Enter')loadResources()});loadResources();
}
async function loadResources(){
  const q=document.querySelector('#resource-q')?.value.trim()||state.resourceQuery||'';state.resourceQuery=q;const params=new URLSearchParams({q,rows:'24'});[['subject','#resource-subject'],['grade','#resource-grade'],['language','#resource-language'],['issue','#resource-issue']].forEach(([k,s])=>{const v=document.querySelector(s)?.value;if(v)params.set(k,v)});const results=document.querySelector('#resource-results');if(results)results.innerHTML=Array.from({length:6},()=>'<div class="skeleton"></div>').join('');
  try{const res=await fetch(`${CONFIG.resourcesEndpoint}?${params}`,{headers:{apikey:CONFIG.supabaseKey,Authorization:`Bearer ${CONFIG.supabaseKey}`}});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();state.resources=data.resources||[];state.resourceMeta=data;const notice=document.querySelector('#resource-notice');notice.className=`notice ${data.demoMode?'warning':'success'}`;notice.textContent=data.message||`${data.source}・第 ${data.page||1} 頁`;renderResourceCards(state.resources,false);}catch(err){document.querySelector('#resource-notice').className='notice danger';document.querySelector('#resource-notice').textContent='資源載入失敗，請檢查網路後重試。';results.innerHTML=`<div class="card empty" style="grid-column:1/-1">${escapeHtml(err.message)}<br><button class="btn btn-secondary" onclick="location.reload()">重新整理</button></div>`;}
}
function renderResourceCards(resources,favoritesOnly){const root=document.querySelector('#resource-results');if(!root)return;if(!resources.length){root.innerHTML='<div class="card empty" style="grid-column:1/-1">找不到符合條件的資源。</div>';return;}root.innerHTML=resources.map(r=>{const fav=state.favorites.some(f=>f.id===r.id);return `<article class="card resource-card"><div class="resource-thumb">${r.thumbnail?`<img src="${escapeHtml(r.thumbnail)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.replaceWith(document.createTextNode('📚'))">`:'<span aria-hidden="true">📚</span>'}</div><div class="card-body"><div class="meta-row"><span class="badge ${r.demo?'demo':'success'}">${escapeHtml(r.source)}</span><span class="badge">${escapeHtml(r.subject||'未標示')}</span></div><h3>${escapeHtml(r.title)}</h3><p>${escapeHtml(r.description||'無摘要')}</p><div class="meta-row"><span class="badge teal">${escapeHtml(r.gradeLabel||((r.grades||[]).map(g=>`${g}年級`).join('、'))||'年級未標示')}</span><span class="badge">${escapeHtml(r.type||'類型未標示')}</span><span class="badge warn">${escapeHtml(r.license||'授權未標示')}</span></div><div class="resource-actions"><button class="btn btn-sm ${fav?'btn-danger':'btn-secondary'}" data-fav="${escapeHtml(r.id)}">${fav?'♥ 已收藏':'♡ 收藏'}</button><button class="btn btn-sm btn-secondary" data-add-resource="${escapeHtml(r.id)}">加入目前教案</button><button class="btn btn-sm btn-secondary" data-copy-citation="${escapeHtml(r.id)}">複製引用</button>${r.sourceUrl?`<a class="btn btn-sm btn-ghost" href="${escapeHtml(r.sourceUrl)}" target="_blank" rel="noopener noreferrer">原始連結 ↗</a>`:''}</div><div class="source-line">更新：${escapeHtml(r.lastUpdated||'未標示')}・語言：${escapeHtml(r.language||'未標示')}</div></div></article>`}).join('');
  root.querySelectorAll('[data-fav]').forEach(b=>b.addEventListener('click',()=>toggleFavorite(findResource(b.dataset.fav))));root.querySelectorAll('[data-add-resource]').forEach(b=>b.addEventListener('click',()=>addResourceToPlan(findResource(b.dataset.addResource))));root.querySelectorAll('[data-copy-citation]').forEach(b=>b.addEventListener('click',()=>copyCitation(findResource(b.dataset.copyCitation))));
  function findResource(id){return [...state.resources,...state.favorites].find(r=>r.id===id)}
}
async function toggleFavorite(r){if(!r)return;const index=state.favorites.findIndex(x=>x.id===r.id);const removing=index>=0;if(removing){state.favorites.splice(index,1);toast('已取消收藏');}else{state.favorites.unshift(r);toast('已加入收藏','success');}persistFavorites();if(state.session&&state.supabase){if(removing)await state.supabase.from('educraft_saved_resources').delete().eq('resource_id',r.id);else await state.supabase.from('educraft_saved_resources').upsert({user_id:state.session.user.id,resource_id:r.id,resource_json:r},{onConflict:'user_id,resource_id'});}if(state.route==='resources')renderResourceCards(state.resourceMeta?state.resources:state.favorites,false);else if(state.route==='my-plans')renderMyPlans();}
function citationText(r){return `${r.title}。${r.source}。${r.sourceUrl||''}（授權：${r.license||'依原始資源標示'}）`;}
async function copyCitation(r){if(!r)return;await navigator.clipboard.writeText(citationText(r));toast('引用文字已複製','success');}
function addResourceToPlan(r){const plan=currentPlan();if(!plan){toast('請先建立或選擇教案。','error');navigate('generator');return;}plan.citations=plan.citations||[];if(!plan.citations.some(c=>c.resourceId===r.id))plan.citations.push({resourceId:r.id,title:r.title,url:r.sourceUrl,source:r.source,license:r.license});plan.updatedAt=nowIso();if(!plan.contentMarkdown.includes(r.title))plan.contentMarkdown+=`\n\n## 引用資源\n- [${r.title}](${r.sourceUrl||'#'})（${r.source}；${r.license||'授權依來源標示'}）`;savePlan(plan);toast('已加入目前教案','success');}

function renderCurriculum(){
  const body=`<div class="notice warning">本頁是可搜尋的「導航索引與教學摘要」，不是官方條文副本。課綱代碼與原文請以國家教育研究院最新版為準。</div><div class="grid grid-3">${OFFICIAL_SOURCES.slice(0,3).map(s=>`<a class="official-link card" href="${s.url}" target="_blank" rel="noopener noreferrer"><span>↗</span><span><strong>${s.title}</strong><small style="display:block;color:var(--muted)">${s.type}・官方原文</small></span></a>`).join('')}</div><div class="card filter-bar" style="margin-top:18px"><input id="curriculum-q" maxlength="80" placeholder="搜尋領域、學習階段或重點"></div><div id="curriculum-list" class="grid grid-2">${curriculumCards(CURRICULUM_INDEX)}</div>`;
  setMain(pageShell('課綱與來源','快速定位領域與學習階段，再前往官方原文核對。',body,'<button class="btn btn-secondary" data-go="sources">資料來源與授權</button>'));bindGoButtons();document.querySelector('#curriculum-q').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelector('#curriculum-list').innerHTML=curriculumCards(CURRICULUM_INDEX.filter(x=>`${x.subject}${x.stage}${x.focus}${x.note}`.toLowerCase().includes(q)))});
}
function curriculumCards(items){return items.map(x=>`<article class="card card-body curriculum-card"><div class="meta-row"><span class="badge teal">${escapeHtml(x.subject)}</span><span class="badge">${escapeHtml(x.stage)}</span></div><h2 style="font-size:19px;margin-top:12px">教學重點索引</h2><p>${escapeHtml(x.focus)}</p><div class="notice" style="font-size:13px">${escapeHtml(x.note)}</div><a href="https://www.naer.edu.tw/PageSyllabus?fid=177" target="_blank" rel="noopener noreferrer">前往官方領綱核對 ↗</a></article>`).join('')||'<div class="card empty">沒有符合的索引。</div>';}
