'use strict';

window.EDUCRAFT_STYLES = {
  competency:{label:'素養導向',framework:'情境—探究—應用—反思',description:'以真實情境、可觀察學習證據與遷移任務組織課程。',stages:['情境導入','探究建構','應用實作','反思遷移'],methods:['十二年國教素養導向','情境任務','可觀察學習證據']},
  fiveE:{label:'5E 探究',framework:'Engage—Explore—Explain—Elaborate—Evaluate',description:'先探索證據再形成解釋，適合自然、數學與跨域探究。',stages:['Engage 引起投入','Explore 探索','Explain 解釋','Elaborate 精緻化','Evaluate 評量'],methods:['5E inquiry cycle','證據導向解釋','探究學習']},
  pbl:{label:'PBL 專題',framework:'驅動問題—探究—原型—發表—反思',description:'以真實問題、長程探究與公開成果建立完整學習歷程。',stages:['提出驅動問題','規劃探究','製作原型','公開發表','回饋反思'],methods:['Project-Based Learning','驅動問題','公開成果']},
  steam:{label:'跨域 STEAM',framework:'Ask—Imagine—Plan—Create—Improve—Share',description:'整合科學、科技、工程、藝術與數學的設計循環。',stages:['Ask 提問','Imagine 想像','Plan 規劃','Create 創作','Improve 改良','Share 分享'],methods:['STEAM design cycle','工程設計','跨領域整合']},
  clil:{label:'雙語 CLIL',framework:'Content—Communication—Cognition—Culture',description:'同時設計學科內容、語言鷹架、思考任務與文化連結。',stages:['Content 內容啟動','Communication 語言鷹架','Cognition 思考任務','Culture 文化連結','成果表達'],methods:['CLIL 4Cs','學科語言鷹架','多模態輸入']},
  udl:{label:'UDL 全方位設計',framework:'投入—表徵—行動與表達',description:'預先設計多種進入、理解與展現學習的方式，降低障礙。',stages:['多元投入','多元表徵','引導練習','多元行動與表達','自我調節'],methods:['Universal Design for Learning','多元投入','多元表徵','多元行動與表達']},
  game:{label:'遊戲化任務',framework:'任務—規則—挑戰—回饋—升級',description:'以任務故事、分級挑戰與即時回饋增加投入，但不以獎勵取代學習。',stages:['任務故事','規則與目標','分級挑戰','即時回饋','成果升級'],methods:['Gameful learning','自主選擇','即時回饋']},
  reading:{label:'閱讀理解',framework:'閱讀前—閱讀中—閱讀後',description:'設計預測、提問、推論、統整、觀點比較與文本證據。',stages:['預測與提問','抓取訊息','推論與統整','觀點比較','表達與延伸'],methods:['閱讀前中後策略','提問與推論','文本證據']},
  sel:{label:'SEL 社會情緒',framework:'連結—辨識—練習—應用—反思',description:'結合安全感、情緒辨識、關係技巧與負責任決策。',stages:['安全連結','情緒辨識','策略示範','情境練習','反思承諾'],methods:['Social Emotional Learning','情緒辨識','關係技巧與決策']},
  explicit:{label:'明確教學',framework:'I do—We do—You do—Check',description:'清楚示範思考歷程，逐步撤除鷹架並快速檢核。',stages:['I do 目標與示範','We do 共同練習','引導練習','You do 獨立練習','快速檢核'],methods:['Explicit instruction','示範思考歷程','逐步撤除鷹架']}
};

const EDUCRAFT_LANGUAGE_PACKS={
  '繁體中文':{draft:false,title:'教案',teacher:'教師引導',student:'學生活動',evidence:'學習證據',headings:{rationale:'設計理念',method:'教學框架與原創說明',curriculum:'課綱對應與官方核對',objectives:'可觀察學習目標',materials:'教材與設備',preparation:'課前準備',differentiation:'差異化與合理調整',assessment:'評量設計',rubric:'評量規準',citations:'引用與授權',checklist:'教師上課前檢核'},review:'所有課綱代碼、多語內容與活動安全須由教師核對。'},
  'English':{draft:false,title:'Lesson Plan',teacher:'Teacher guidance',student:'Student activity',evidence:'Learning evidence',headings:{rationale:'Design rationale',method:'Methodology and originality',curriculum:'Curriculum alignment',objectives:'Observable learning objectives',materials:'Materials',preparation:'Preparation',differentiation:'Differentiation and accommodations',assessment:'Assessment design',rubric:'Rubric',citations:'Sources and licensing',checklist:'Teacher review checklist'},review:'The teacher must verify curriculum alignment, language accuracy, licensing, privacy and safety.'},
  '日本語':{draft:false,title:'授業案',teacher:'教師の支援',student:'児童の活動',evidence:'学習の証拠',headings:{rationale:'設計意図',method:'指導法と独自性',curriculum:'カリキュラムとの対応',objectives:'観察可能な学習目標',materials:'教材・教具',preparation:'事前準備',differentiation:'個別最適化と合理的配慮',assessment:'評価計画',rubric:'評価規準',citations:'出典とライセンス',checklist:'授業前チェック'},review:'教師が公式カリキュラム、言語、著作権、個人情報、安全面を確認してください。'},
  '한국어':{draft:false,title:'수업 지도안',teacher:'교사 안내',student:'학생 활동',evidence:'학습 증거',headings:{rationale:'설계 취지',method:'교수법과 독창성',curriculum:'교육과정 연계',objectives:'관찰 가능한 학습 목표',materials:'자료와 준비물',preparation:'수업 전 준비',differentiation:'차별화와 합리적 지원',assessment:'평가 설계',rubric:'평가 기준',citations:'출처와 라이선스',checklist:'교사 검토 목록'},review:'교사가 공식 교육과정, 언어, 저작권, 개인정보와 안전을 확인해야 합니다.'},
  'Tiếng Việt':{draft:false,title:'Kế hoạch bài dạy',teacher:'Hướng dẫn của giáo viên',student:'Hoạt động của học sinh',evidence:'Minh chứng học tập',headings:{rationale:'Cơ sở thiết kế',method:'Phương pháp và tính nguyên bản',curriculum:'Đối chiếu chương trình',objectives:'Mục tiêu có thể quan sát',materials:'Học liệu và thiết bị',preparation:'Chuẩn bị',differentiation:'Phân hóa và hỗ trợ hợp lý',assessment:'Thiết kế đánh giá',rubric:'Tiêu chí đánh giá',citations:'Nguồn và giấy phép',checklist:'Danh sách kiểm tra của giáo viên'},review:'Giáo viên phải kiểm tra chương trình, ngôn ngữ, bản quyền, dữ liệu cá nhân và an toàn.'},
  'Bahasa Indonesia':{draft:false,title:'Rencana Pembelajaran',teacher:'Panduan guru',student:'Aktivitas siswa',evidence:'Bukti belajar',headings:{rationale:'Dasar perancangan',method:'Metodologi dan orisinalitas',curriculum:'Kesesuaian kurikulum',objectives:'Tujuan belajar teramati',materials:'Materi dan alat',preparation:'Persiapan',differentiation:'Diferensiasi dan akomodasi',assessment:'Desain asesmen',rubric:'Rubrik',citations:'Sumber dan lisensi',checklist:'Daftar periksa guru'},review:'Guru harus memeriksa kurikulum, bahasa, lisensi, privasi dan keselamatan.'},
  'ภาษาไทย':{draft:false,title:'แผนการสอน',teacher:'แนวทางครู',student:'กิจกรรมนักเรียน',evidence:'หลักฐานการเรียนรู้',headings:{rationale:'แนวคิดการออกแบบ',method:'วิธีสอนและความเป็นต้นฉบับ',curriculum:'ความเชื่อมโยงหลักสูตร',objectives:'เป้าหมายที่สังเกตได้',materials:'สื่อและอุปกรณ์',preparation:'การเตรียม',differentiation:'การปรับตามความแตกต่าง',assessment:'การออกแบบการประเมิน',rubric:'เกณฑ์ประเมิน',citations:'แหล่งอ้างอิงและสิทธิ์',checklist:'รายการตรวจสอบครู'},review:'ครูต้องตรวจสอบหลักสูตร ภาษา ลิขสิทธิ์ ข้อมูลส่วนบุคคล และความปลอดภัย'}
};

function languagePack(language){return EDUCRAFT_LANGUAGE_PACKS[language]||{...EDUCRAFT_LANGUAGE_PACKS['繁體中文'],draft:true,review:`「${language}」內容目前為結構化草稿，必須由母語者或具資格教師完整校訂。`}}
function selectedChoices(name){const group=document.querySelector(`[data-choice-group="${name}"]`);return group?[...group.querySelectorAll('[aria-pressed="true"]')].map(x=>x.dataset.choice):[]}
function selectedStyle(){return document.querySelector('[data-style][aria-pressed="true"]')?.dataset.style||'competency'}

renderGenerator=function(){
  const choices=(items,name)=>`<div class="choice-list" data-choice-group="${name}">${items.map(i=>`<button type="button" class="choice" aria-pressed="false" data-choice="${escapeHtml(i)}">${escapeHtml(i)}</button>`).join('')}</div>`;
  const styles=Object.entries(window.EDUCRAFT_STYLES).map(([key,s],index)=>`<button type="button" class="style-option" data-style="${key}" aria-pressed="${index===0}"><strong>${escapeHtml(s.label)}</strong><span>${escapeHtml(s.description)}</span></button>`).join('');
  const body=`<div class="notice">每種風格會產生不同教學階段與教師引導，不只是改名稱。平台只參考教學框架與專業呈現，不擷取或拼貼網路教案全文。</div><form id="generator-form" class="card card-body"><div class="form-grid"><div class="field"><label for="gen-grade">年級</label><select id="gen-grade" required>${[1,2,3,4,5,6].map(g=>`<option value="${g}">${g}年級</option>`).join('')}</select></div><div class="field"><label for="gen-subject">科目</label><select id="gen-subject" required>${SUBJECTS.map(s=>`<option>${s}</option>`).join('')}</select></div><div class="field full"><label for="gen-topic">教學主題</label><input id="gen-topic" required maxlength="160" placeholder="例如：認識臺灣河川生態"></div><div class="field full"><label>教案風格</label><div class="style-grid">${styles}</div></div><div class="field"><label for="gen-sessions">節數</label><input id="gen-sessions" type="number" min="1" max="12" value="2"></div><div class="field"><label for="gen-minutes">每節分鐘</label><input id="gen-minutes" type="number" min="20" max="90" value="40"></div><div class="field"><label for="gen-language">課堂主要語言</label><select id="gen-language">${LANGUAGES.map(s=>`<option>${s}</option>`).join('')}</select></div><div class="field"><label for="gen-output-language">教案輸出語言</label><select id="gen-output-language">${EDUCRAFT_OUTPUT_LANGUAGES.map(s=>`<option>${s}</option>`).join('')}</select><small class="language-note">臺語、客語、族語、新住民語與臺灣手語輸出會標示為待專業教師校訂的草稿。</small></div><div class="field"><label for="gen-tone">呈現風格</label><select id="gen-tone"><option>專業正式</option><option>教師實務版</option><option>簡潔表格式</option><option>溫暖引導式</option><option>研究與觀課版</option></select></div><div class="field"><label for="gen-level">學生程度</label><input id="gen-level" maxlength="300" placeholder="例如：程度落差較大"></div><div class="field full"><label for="gen-context">班級特性</label><textarea id="gen-context" maxlength="800" placeholder="班級人數、互動習慣、在地脈絡等"></textarea></div><div class="field full"><label for="gen-prior">先備知識</label><textarea id="gen-prior" maxlength="800"></textarea></div><div class="field full"><label for="gen-needs">特殊需求與合理調整</label><textarea id="gen-needs" maxlength="500" placeholder="使用去識別化描述，不輸入學生姓名或診斷資料"></textarea></div><div class="field full"><label for="gen-equipment">設備與材料</label><input id="gen-equipment" maxlength="500" placeholder="投影機、平板、實驗器材…"></div><div class="field full"><label>議題融入</label>${choices(ISSUES,'issues')}</div><div class="field full"><label>評量方式</label>${choices(ASSESSMENTS,'assessments')}</div></div><div class="originality-box" style="margin-top:18px"><strong>原創性規則</strong><p>產生器依你的條件與公開教學框架獨立組合內容；不仿寫單一民間教案、不擷取學習單文字。加入外部資源時，系統會保存來源與授權。</p></div><div class="header-actions" style="justify-content:flex-end;margin-top:20px"><button id="generate-submit" class="btn btn-primary" type="submit">✣ 產生原創教案</button></div></form>`;
  setMain(pageShell('多語與多風格教案產生器','選擇教學框架、輸出語言與班級條件，建立具有清楚原創邊界的教案。',body));
  document.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',()=>b.setAttribute('aria-pressed',b.getAttribute('aria-pressed')!=='true')));
  document.querySelectorAll('[data-style]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-style]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))}));
  document.querySelector('#generator-form').addEventListener('submit',generatePlan);
};

function styleStageText(stage,payload){
  const topic=payload.topic,pack=languagePack(payload.outputLanguage),language=payload.outputLanguage;
  if(language==='English')return{teacher:`Guide the class through “${stage}” using a meaningful context related to “${topic}”. Model how to use evidence and ask students to explain their choices.`,student:`Work individually and collaboratively to investigate, create, explain and revise a response about “${topic}”.`,evidence:`${pack.evidence}: notes, oral explanation, product, performance or exit ticket.`};
  if(language==='日本語')return{teacher:`「${topic}」に関する意味のある状況を用いて「${stage}」を進め、根拠と考え方を明示する。`,student:`個人または協働で探究し、成果を説明・修正する。`,evidence:`${pack.evidence}：記録、説明、作品、実演、振り返り。`};
  if(language==='한국어')return{teacher:`‘${topic}’과 관련된 실제 맥락으로 ‘${stage}’ 단계를 안내하고 근거와 사고 과정을 모델링한다.`,student:`개인 및 협력 활동으로 탐구하고 결과를 설명·수정한다.`,evidence:`${pack.evidence}: 기록, 구두 설명, 작품, 수행 또는 성찰.`};
  if(language==='Tiếng Việt')return{teacher:`Hướng dẫn giai đoạn “${stage}” bằng bối cảnh có ý nghĩa liên quan đến “${topic}”, làm mẫu cách dùng minh chứng.`,student:`Làm việc cá nhân và hợp tác để tìm hiểu, tạo sản phẩm, giải thích và chỉnh sửa.`,evidence:`${pack.evidence}: ghi chép, trình bày, sản phẩm, thực hành hoặc phiếu cuối giờ.`};
  if(language==='Bahasa Indonesia')return{teacher:`Bimbing tahap “${stage}” melalui konteks bermakna tentang “${topic}” dan contohkan penggunaan bukti.`,student:`Belajar mandiri dan kolaboratif untuk menyelidiki, membuat, menjelaskan, dan merevisi hasil.`,evidence:`${pack.evidence}: catatan, penjelasan, produk, unjuk kerja, atau refleksi.`};
  if(language==='ภาษาไทย')return{teacher:`ดำเนินขั้น “${stage}” ผ่านบริบทที่มีความหมายเกี่ยวกับ “${topic}” และสาธิตการใช้หลักฐาน`,student:`ทำงานรายบุคคลและร่วมมือเพื่อสำรวจ สร้าง อธิบาย และปรับปรุงผลงาน`,evidence:`${pack.evidence}: บันทึก คำอธิบาย ผลงาน การปฏิบัติ หรือบัตรออกจากชั้นเรียน`};
  return{teacher:`以「${topic}」的真實情境引導「${stage}」，示範如何使用證據、說明理由並依學生回應調整鷹架。`,student:`透過個別思考與合作任務完成探究、創作、說明及修正。`,evidence:`${pack.evidence}：任務紀錄、口語說明、作品、實作表現或離堂票。`};
}

function applyStyleToPlan(plan,payload){
  const style=window.EDUCRAFT_STYLES[payload.style]||window.EDUCRAFT_STYLES.competency,pack=languagePack(payload.outputLanguage);
  plan.meta=plan.meta||{};plan.meta.input={...(plan.meta.input||{}),...payload};plan.meta.generatedBy='EduCraft 原創模板引擎';plan.meta.styleKey=payload.style;plan.meta.styleLabel=style.label;plan.meta.outputLanguage=payload.outputLanguage;
  plan.title=`${payload.topic}｜${style.label}${pack.title}`;
  plan.designRationale=`本教案以「${style.framework}」組織學習歷程，依本次年級、科目、班級與語言條件獨立組合。平台只參考公開教學框架的專業方法，不複製特定民間教案文字、活動或學習單。${pack.review}`;
  plan.methodologyReferences=style.methods.map(name=>({name,usage:'參考框架原則與流程；未複製特定作者的教案內容。'}));
  plan.originality={statement:'本教案依使用者輸入與 EduCraft 規則獨立產生。',separation:['不抓取或拼貼網路教案全文','不仿寫單一作者的獨特表達','外部素材必須保留來源與授權','發布前由教師加入班級與在地決策'],reviewRequired:true};
  const sessionCount=Math.max(1,payload.sessions),minutes=Math.max(20,payload.minutesPerSession),per=Math.max(3,Math.floor(minutes/style.stages.length));
  plan.sessions=Array.from({length:sessionCount},(_,index)=>({index:index+1,title:`${index+1}. ${style.label}｜${index===0?'建立問題與共同語言':index===sessionCount-1?'成果整合、評量與遷移':'深化探究與修正'}`,minutes,stages:style.stages.map((stage,stageIndex)=>({name:stage,minutes:stageIndex===style.stages.length-1?minutes-per*(style.stages.length-1):per,...styleStageText(stage,payload)}))}));
  plan.multilingualSupport=[{language:payload.outputLanguage,original:`${payload.topic}核心概念與任務語句`,draft:pack.draft?'結構化草稿；須由母語者或具資格教師完整校訂。':'已套用對應語言的通用教學語句，仍須依年級與語境校訂。',teacherRevision:''},{language:'繁體中文',original:`${payload.topic}概念說明`,draft:'作為教師核對與跨語言對照的中文基準。',teacherRevision:''},{language:'English',original:`Key vocabulary for ${payload.topic}`,draft:'Prepare a bilingual word bank, sentence frames and multimodal supports.',teacherRevision:''}];
  plan.teacherReviewChecklist=[...(plan.teacherReviewChecklist||[]),'確認未複製未授權的民間教案內容','補上所有外部參考來源與授權','確認公開版本未含學生個資'];
  return plan;
}

generatePlan=async function(event){
  event.preventDefault();const payload={grade:Number(document.querySelector('#gen-grade').value),subject:document.querySelector('#gen-subject').value,topic:document.querySelector('#gen-topic').value.trim(),style:selectedStyle(),sessions:Number(document.querySelector('#gen-sessions').value),minutesPerSession:Number(document.querySelector('#gen-minutes').value),language:document.querySelector('#gen-language').value,outputLanguage:document.querySelector('#gen-output-language').value,tone:document.querySelector('#gen-tone').value,studentLevel:document.querySelector('#gen-level').value,classContext:document.querySelector('#gen-context').value,priorKnowledge:document.querySelector('#gen-prior').value,specialNeeds:document.querySelector('#gen-needs').value,equipment:document.querySelector('#gen-equipment').value,issues:selectedChoices('issues'),assessments:selectedChoices('assessments')};
  const button=document.querySelector('#generate-submit');button.disabled=true;button.textContent='產生中…';
  try{const response=await fetch(CONFIG.generateEndpoint,{method:'POST',headers:{'Content-Type':'application/json',apikey:CONFIG.supabaseKey,Authorization:`Bearer ${CONFIG.supabaseKey}`},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.message||data.error||'產生失敗');const generated=applyStyleToPlan(data.plan,payload);const plan={id:uid(),title:generated.title,subject:payload.subject,grade:payload.grade,topic:payload.topic,language:payload.language,outputLanguage:payload.outputLanguage,teachingStyle:payload.style,tone:payload.tone,contentMarkdown:communityPlanToMarkdown(generated),planJson:generated,tags:payload.issues||[],status:'draft',visibility:'private',publicSlug:'',publishedAt:null,license:'CC BY-NC-SA 4.0',publicSummary:'',originalityNote:generated.originality.statement,methodology:generated.methodologyReferences,citations:generated.citations||[],versions:[],createdAt:nowIso(),updatedAt:nowIso(),sourceMode:'template'};state.plans.unshift(plan);setCurrentPlan(plan.id);persistPlans();if(state.session)await upsertCloudPlan(plan);toast(`已建立「${window.EDUCRAFT_STYLES[payload.style].label}」教案。`,'success');navigate('editor')}catch(error){toast(error.message||'產生失敗','error')}finally{button.disabled=false;button.textContent='✣ 產生原創教案'}
};

function communityPlanToMarkdown(plan){
  const input=plan.meta?.input||{},pack=languagePack(input.outputLanguage||input.language||'繁體中文'),h=pack.headings,lines=[`# ${plan.title||input.topic||pack.title}`,`> ${input.grade||''}年級・${input.subject||''}・${input.sessions||''}節 × ${input.minutesPerSession||''}分鐘`,`> ${plan.meta?.styleLabel||''}｜${input.outputLanguage||input.language||'繁體中文'}｜${pack.review}`,'',`## ${h.rationale}`,plan.designRationale||'','',`## ${h.method}`,`- 原創聲明：${plan.originality?.statement||''}`,...(plan.originality?.separation||[]).map(x=>`- ${x}`),...(plan.methodologyReferences||[]).map(x=>`- **${x.name}**：${x.usage}`),'',`## ${h.curriculum}`,`- 學習階段：${plan.curriculumAlignment?.stage||''}`,`- 領域／科目：${plan.curriculumAlignment?.subject||''}`,`- 核對提醒：${plan.curriculumAlignment?.note||''}`,...(plan.curriculumAlignment?.officialSources||[]).map(x=>`- [${x.title}](${x.url})`),'',`## ${h.objectives}`,...(plan.learningObjectives||[]).map(x=>`- **${x.dimension}**：${x.objective}（${pack.evidence}：${x.evidence}）`),'',`## ${h.materials}`,...(plan.materials||[]).map(x=>`- ${x}`),'',`## ${h.preparation}`,...(plan.preparation||[]).map(x=>`- ${x}`),''];
  for(const session of plan.sessions||[]){lines.push(`## ${session.title}（${session.minutes}分鐘）`);for(const stage of session.stages||[])lines.push(`### ${stage.name}（${stage.minutes}分鐘）`,`- ${pack.teacher}：${stage.teacherScript||stage.teacher||''}`,`- ${pack.student}：${stage.studentActivity||stage.student||''}`,`- ${pack.evidence}：${stage.evidence||''}`,'')}
  lines.push(`## ${h.differentiation}`,`- 進階挑戰：${plan.differentiation?.advanced||''}`,`- 學習支持：${plan.differentiation?.support||''}`,`- 合理調整：${plan.differentiation?.specialNeeds||''}`,'',`## ${h.assessment}`,'### 形成性評量',...(plan.formativeAssessment||[]).map(x=>`- ${x}`),'### 總結性評量',...(plan.summativeAssessment||[]).map(x=>`- ${x}`),'',`## ${h.rubric}`,'| 指標 | 優秀 | 達標 | 發展中 | 起步 |','|---|---|---|---|---|',...(plan.rubric||[]).map(x=>`| ${x.criterion} | ${x.excellent} | ${x.proficient} | ${x.developing} | ${x.beginning} |`),'',`## ${h.citations}`,...(plan.citations||[]).map(x=>`- [${x.title}](${x.url})（${x.license||'依來源標示'}）`),'',`## ${h.checklist}`,...(plan.teacherReviewChecklist||[]).map(x=>`- [ ] ${x}`));return lines.join('\n');
}

planToMarkdown=function(plan){return communityPlanToMarkdown(plan)};

function visibilityBadge(plan){const value=plan.visibility||'private';return value==='public'?'<span class="badge visibility-public">🌐 公開</span>':value==='unlisted'?'<span class="badge visibility-unlisted">🔗 非公開連結</span>':'<span class="badge visibility-private">🔒 私人</span>'}

renderMyPlans=function(){
  const list=[...state.plans].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)),privatePlans=list.filter(x=>(x.visibility||'private')!=='public'),publicPlans=list.filter(x=>x.visibility==='public');
  const row=plan=>`<article class="card plan-row"><div><h3>${escapeHtml(plan.title)}</h3><p>${escapeHtml(plan.subject)}・${plan.grade||'未設定'}年級・${formatDate(plan.updatedAt)}</p><div class="meta-row" style="margin-top:7px">${visibilityBadge(plan)}<span class="badge teal">${escapeHtml(window.EDUCRAFT_STYLES[plan.teachingStyle]?.label||plan.teachingStyle||'一般教案')}</span><span class="badge">${escapeHtml(plan.outputLanguage||plan.language||'繁體中文')}</span><span class="badge warn">${escapeHtml(plan.license||'CC BY-NC-SA 4.0')}</span></div></div><div class="header-actions"><button class="btn btn-primary btn-sm" data-open="${plan.id}">開啟</button>${plan.visibility==='public'?`<a class="btn btn-secondary btn-sm" href="#public-plan/${encodeURIComponent(plan.publicSlug||'')}">公開頁</a><button class="btn btn-secondary btn-sm" data-unpublish="${plan.id}">撤回公開</button>`:`<button class="btn btn-teal btn-sm" data-publish="${plan.id}">發布</button>`}<button class="btn btn-danger btn-sm" data-delete="${plan.id}">刪除</button></div></article>`;
  const body=`<div class="privacy-split"><section><div class="privacy-label">🔒 個人教案檔</div><h2>私人與非公開教案（${privatePlans.length}）</h2><p>只有你的帳號可讀取；未登入時保存在目前瀏覽器。</p><div class="plan-list">${privatePlans.length?privatePlans.map(row).join(''):'<div class="card empty">尚無私人教案。</div>'}</div></section><section><div class="privacy-label public">🌐 公開資料檔</div><h2>已發布教案（${publicPlans.length}）</h2><p>只有按下發布並確認授權的版本才會進入公開教案庫。</p><div class="plan-list">${publicPlans.length?publicPlans.map(row).join(''):'<div class="card empty">尚未發布公開教案。</div>'}</div></section></div><section style="margin-top:24px"><h2>收藏資源（${state.favorites.length}）</h2><div class="plan-list">${state.favorites.length?state.favorites.map(r=>`<article class="card plan-row"><div><h3>${escapeHtml(r.title)}</h3><p>${escapeHtml(r.source)}・${escapeHtml(r.license||'')}</p></div><div class="header-actions"><button class="btn btn-secondary btn-sm" data-fav-add="${escapeHtml(r.id)}">加入教案</button><button class="btn btn-danger btn-sm" data-fav-remove="${escapeHtml(r.id)}">移除</button></div></article>`).join(''):'<div class="card empty">尚無收藏。</div>'}</div></section>`;
  setMain(pageShell('我的教案、私人檔與公開檔','私人資料不會自動公開；每份公開教案均可個別撤回。',body,'<button id="backup-all" class="btn btn-secondary">匯出完整備份</button><label class="btn btn-secondary">匯入備份<input id="restore-all" type="file" accept="application/json" hidden></label>'));
  document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>{setCurrentPlan(b.dataset.open);navigate('editor')}));document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>deletePlan(b.dataset.delete)));document.querySelectorAll('[data-publish]').forEach(b=>b.addEventListener('click',()=>openPublishDialog(state.plans.find(x=>x.id===b.dataset.publish))));document.querySelectorAll('[data-unpublish]').forEach(b=>b.addEventListener('click',()=>unpublishPlan(state.plans.find(x=>x.id===b.dataset.unpublish))));document.querySelectorAll('[data-fav-add]').forEach(b=>b.addEventListener('click',()=>addResourceToPlan(state.favorites.find(r=>r.id===b.dataset.favAdd))));document.querySelectorAll('[data-fav-remove]').forEach(b=>b.addEventListener('click',()=>toggleFavorite(state.favorites.find(r=>r.id===b.dataset.favRemove))));document.querySelector('#backup-all').addEventListener('click',backupAll);document.querySelector('#restore-all').addEventListener('change',restoreAll);
};

async function openPublishDialog(plan){
  if(!plan)return;if(!state.session){toast('請先註冊或登入，才能建立公開資料檔。','error');navigate('account');return}
  const {data:profile}=await state.supabase.from('educraft_public_profiles').select('*').eq('user_id',state.session.user.id).eq('is_listed',true).maybeSingle();if(!profile){toast('請先完成並啟用公開教師名片。','error');navigate('account');return}
  document.querySelector('#publish-dialog')?.remove();const dialog=document.createElement('dialog');dialog.id='publish-dialog';dialog.className='modal publish-dialog';const suggested=plan.publicSlug||`${slugify(plan.title)}-${Math.random().toString(36).slice(2,6)}`.slice(0,64);dialog.innerHTML=`<form method="dialog" class="modal-card" id="publish-form"><button class="modal-close" value="cancel" aria-label="關閉">✕</button><h2>發布公開教案</h2><div class="notice warning">公開版本可被任何人閱讀。請先移除學生姓名、照片、聯絡資訊、診斷及其他敏感資料。</div><div class="field"><label for="publish-summary">公開摘要</label><textarea id="publish-summary" required maxlength="500">${escapeHtml(plan.publicSummary||plan.topic||'')}</textarea></div><div class="field"><label for="publish-slug">公開網址代碼</label><input id="publish-slug" required maxlength="64" pattern="[a-z0-9][a-z0-9-]{2,63}" value="${escapeHtml(suggested)}"></div><div class="field"><label for="publish-license">授權</label><select id="publish-license">${['All rights reserved','CC BY 4.0','CC BY-SA 4.0','CC BY-NC 4.0','CC BY-NC-SA 4.0','CC0 1.0'].map(x=>`<option ${x===(plan.license||'CC BY-NC-SA 4.0')?'selected':''}>${x}</option>`).join('')}</select></div><label class="check"><input id="publish-rights" type="checkbox" required>我確認內容由我創作或具有合法利用權，所有外部來源與授權均已標示。</label><label class="check"><input id="publish-privacy" type="checkbox" required>我確認公開版本不含學生可識別個資或不必要的敏感資訊。</label><div class="header-actions"><button class="btn btn-secondary" value="cancel">取消</button><button class="btn btn-teal" type="submit" value="default">確認發布</button></div></form>`;document.body.append(dialog);dialog.showModal();dialog.querySelector('#publish-form').addEventListener('submit',event=>publishPlan(event,plan,dialog));dialog.addEventListener('close',()=>dialog.remove(),{once:true});
}

async function publishPlan(event,plan,dialog){event.preventDefault();const slug=document.querySelector('#publish-slug').value.trim().toLowerCase();if(!/^[a-z0-9][a-z0-9-]{2,63}$/.test(slug)){toast('公開網址只能使用小寫英文、數字與連字號。','error');return}plan.visibility='public';plan.publicSlug=slug;plan.publishedAt=nowIso();plan.license=document.querySelector('#publish-license').value;plan.publicSummary=document.querySelector('#publish-summary').value.trim();plan.originalityNote=plan.originalityNote||plan.planJson?.originality?.statement||'此教案由作者依教學框架獨立設計；外部資源另行標示。';plan.methodology=plan.methodology||plan.planJson?.methodologyReferences||[];plan.updatedAt=nowIso();persistPlans();const result=await upsertCloudPlan(plan);if(!result){plan.visibility='private';plan.publishedAt=null;persistPlans();return}dialog.close();toast('教案已發布至公開教案庫。','success');renderMyPlans()}

async function unpublishPlan(plan){if(!plan||!confirm(`確定撤回「${plan.title}」的公開版本？`))return;plan.visibility='private';plan.publishedAt=null;plan.updatedAt=nowIso();persistPlans();await upsertCloudPlan(plan);toast('公開版本已撤回，私人教案仍保留。','success');renderMyPlans()}

upsertCloudPlan=async function(plan){
  if(!state.session||!state.supabase)return null;state.sync='同步中…';updateSyncUi();const row={user_id:state.session.user.id,client_id:plan.id,title:plan.title,subject:plan.subject||'',grade:plan.grade||null,topic:plan.topic||'',language:plan.language||'繁體中文',output_language:plan.outputLanguage||plan.language||'繁體中文',content_markdown:plan.contentMarkdown||'',plan_json:plan.planJson||{},citations_json:plan.citations||[],tags:plan.tags||[],status:plan.status||'draft',source_mode:['template','ai','manual'].includes(plan.sourceMode)?plan.sourceMode:'manual',visibility:plan.visibility||'private',public_slug:plan.publicSlug||null,published_at:plan.visibility==='public'?(plan.publishedAt||nowIso()):null,license:plan.license||'CC BY-NC-SA 4.0',teaching_style:plan.teachingStyle||'competency',originality_note:plan.originalityNote||'',methodology_json:plan.methodology||[],public_summary:plan.publicSummary||'',cover_emoji:plan.coverEmoji||'📝'};
  const {data,error}=await state.supabase.from('educraft_lesson_plans').upsert(row,{onConflict:'user_id,client_id'}).select().single();if(error){state.sync='同步失敗，本機已保存';updateSyncUi();toast(`雲端同步失敗：${error.message||'本機資料仍安全'}`,'error');return null}plan.cloudId=data.id;plan.cloudUpdatedAt=data.updated_at;persistPlans();state.sync='已同步';updateSyncUi();return data;
};

syncCloud=async function(){
  if(!state.session||!state.supabase)return;state.sync='同步中…';updateSyncUi();const userId=state.session.user.id;
  try{const [plansResult,versionsResult]=await Promise.all([state.supabase.from('educraft_lesson_plans').select('*').eq('user_id',userId).order('updated_at',{ascending:false}),state.supabase.from('educraft_lesson_plan_versions').select('*').eq('user_id',userId).order('version_number',{ascending:true})]);if(plansResult.error)throw plansResult.error;if(versionsResult.error)throw versionsResult.error;const cloud=plansResult.data||[],versions=versionsResult.data||[];
    for(const row of cloud){const remoteVersions=versions.filter(v=>v.lesson_plan_id===row.id).map(v=>({id:v.id,cloudId:v.id,number:v.version_number,title:v.title,contentMarkdown:v.content_markdown,planJson:v.plan_json||{},createdAt:v.created_at}));const mapped={id:row.client_id||uid(),cloudId:row.id,title:row.title,subject:row.subject,grade:row.grade,topic:row.topic,language:row.language,outputLanguage:row.output_language,teachingStyle:row.teaching_style,contentMarkdown:row.content_markdown,planJson:row.plan_json||{},citations:row.citations_json||[],tags:row.tags||[],status:row.status,sourceMode:row.source_mode,visibility:row.visibility||'private',publicSlug:row.public_slug||'',publishedAt:row.published_at,license:row.license,originalityNote:row.originality_note||'',methodology:row.methodology_json||[],publicSummary:row.public_summary||'',coverEmoji:row.cover_emoji||'📝',versions:remoteVersions,createdAt:row.created_at,updatedAt:row.updated_at};const local=state.plans.find(p=>p.id===mapped.id);if(!local)state.plans.push(mapped);else if(new Date(mapped.updatedAt)>new Date(local.updatedAt||0))Object.assign(local,mapped);else{for(const version of remoteVersions)if(!(local.versions||[]).some(x=>x.cloudId===version.cloudId))(local.versions||(local.versions=[])).push(version)}}
    for(const plan of state.plans)await upsertCloudPlan(plan);await syncFavorites();persistPlans();persistFavorites();state.sync='已同步';updateSyncUi();renderRoute();
  }catch(error){state.sync='同步失敗，本機已保存';updateSyncUi();toast(`同步失敗：${error.message||'本機資料仍安全'}`,'error')}
};

const baseRenderSettings=renderSettings;
renderSettings=function(){baseRenderSettings();const login=document.querySelector('#login-settings');if(login){login.textContent='前往註冊／登入頁';login.onclick=()=>navigate('account')}};
