-- Applied to project goedzzhhvvnfczgnkqlv on 2026-08-16.
-- Isolated QueueHub production schema. Existing non-QueueHub tables are untouched.
create extension if not exists pgcrypto;

create table public.queuehub_venues(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,timezone text not null default 'Asia/Taipei',capacity_target integer not null default 3000 check(capacity_target>0),created_at timestamptz not null default now());
create table public.queuehub_restaurants(id uuid primary key default gen_random_uuid(),venue_id uuid not null references public.queuehub_venues(id) on delete cascade,slug text not null,name text not null,category text not null,zone text,is_active boolean not null default true,avg_seconds_per_ticket integer not null default 45 check(avg_seconds_per_ticket>0),created_at timestamptz not null default now(),unique(venue_id,slug));
create table public.queuehub_queue_sessions(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.queuehub_restaurants(id) on delete cascade,business_date date not null,label text not null default 'default',started_at timestamptz not null default now(),ended_at timestamptz,unique(restaurant_id,business_date,label));
create table public.queuehub_queue_status(restaurant_id uuid primary key references public.queuehub_restaurants(id) on delete cascade,queue_session_id uuid not null references public.queuehub_queue_sessions(id) on delete cascade,current_number integer not null default 0 check(current_number>=0),recent_numbers integer[] not null default '{}',state text not null default 'open' check(state in('open','paused','closed')),source text not null default 'manual' check(source in('api','webhook','manual','gateway')),version bigint not null default 0,updated_at timestamptz not null default now());
create table public.queuehub_queue_events(id uuid primary key default gen_random_uuid(),restaurant_id uuid not null references public.queuehub_restaurants(id) on delete cascade,queue_session_id uuid not null references public.queuehub_queue_sessions(id) on delete cascade,sequence bigint not null,event_type text not null check(event_type in('called','skipped','paused','resumed','reset')),number integer,source text not null check(source in('api','webhook','manual','gateway')),actor_user_id uuid references auth.users(id) on delete set null,occurred_at timestamptz not null default now(),idempotency_key text,unique(restaurant_id,queue_session_id,sequence),unique(idempotency_key));
create table public.queuehub_staff_members(user_id uuid not null references auth.users(id) on delete cascade,venue_id uuid not null references public.queuehub_venues(id) on delete cascade,role text not null check(role in('viewer','operator','manager','admin')),is_active boolean not null default true,created_at timestamptz not null default now(),primary key(user_id,venue_id));
create table public.queuehub_integration_configs(restaurant_id uuid primary key references public.queuehub_restaurants(id) on delete cascade,integration_type text not null check(integration_type in('api','webhook','manual','gateway')),api_endpoint text,webhook_path text,polling_interval_seconds integer check(polling_interval_seconds is null or polling_interval_seconds>=1),api_key_secret_name text,gateway_device_id text,enabled boolean not null default true,updated_at timestamptz not null default now());

create index queuehub_restaurants_venue_active_idx on public.queuehub_restaurants(venue_id,is_active);
create index queuehub_sessions_restaurant_date_idx on public.queuehub_queue_sessions(restaurant_id,business_date desc);
create index queuehub_events_restaurant_session_seq_idx on public.queuehub_queue_events(restaurant_id,queue_session_id,sequence desc);
create index queuehub_events_occurred_idx on public.queuehub_queue_events(occurred_at desc);
create index queuehub_staff_venue_active_idx on public.queuehub_staff_members(venue_id,is_active,role);

alter table public.queuehub_venues enable row level security;alter table public.queuehub_restaurants enable row level security;alter table public.queuehub_queue_sessions enable row level security;alter table public.queuehub_queue_status enable row level security;alter table public.queuehub_queue_events enable row level security;alter table public.queuehub_staff_members enable row level security;alter table public.queuehub_integration_configs enable row level security;
create policy queuehub_public_read_venues on public.queuehub_venues for select to anon,authenticated using(true);
create policy queuehub_public_read_active_restaurants on public.queuehub_restaurants for select to anon,authenticated using(is_active=true);
create policy queuehub_public_read_queue_status on public.queuehub_queue_status for select to anon,authenticated using(exists(select 1 from public.queuehub_restaurants r where r.id=restaurant_id and r.is_active=true));
create policy queuehub_staff_read_self on public.queuehub_staff_members for select to authenticated using(user_id=auth.uid());
create policy queuehub_staff_read_events on public.queuehub_queue_events for select to authenticated using(exists(select 1 from public.queuehub_restaurants r join public.queuehub_staff_members m on m.venue_id=r.venue_id where r.id=restaurant_id and m.user_id=auth.uid() and m.is_active));
create policy queuehub_manager_read_integrations on public.queuehub_integration_configs for select to authenticated using(exists(select 1 from public.queuehub_restaurants r join public.queuehub_staff_members m on m.venue_id=r.venue_id where r.id=restaurant_id and m.user_id=auth.uid() and m.is_active and m.role in('manager','admin')));
revoke all on public.queuehub_venues,public.queuehub_restaurants,public.queuehub_queue_sessions,public.queuehub_queue_status,public.queuehub_queue_events,public.queuehub_staff_members,public.queuehub_integration_configs from anon,authenticated;
grant select on public.queuehub_venues,public.queuehub_restaurants,public.queuehub_queue_status to anon,authenticated;
grant select on public.queuehub_staff_members,public.queuehub_queue_events,public.queuehub_integration_configs to authenticated;

insert into public.queuehub_venues(slug,name,timezone,capacity_target) values('beichen','北辰休息站（Demo）','Asia/Taipei',3000);
insert into public.queuehub_restaurants(venue_id,slug,name,category,avg_seconds_per_ticket,is_active) select v.id,x.slug,x.name,x.category,x.avg,true from public.queuehub_venues v cross join(values('harbor-noodles','港町麵屋','麵食',45),('sunrise-bento','日光便當','便當',50),('forest-curry','森野咖哩','飯類',55),('cloud-burger','雲朵漢堡','速食',38),('stone-hotpot','石庭小鍋','鍋物',65),('field-rice','田野食堂','飯類',48),('north-coffee','北辰咖啡','飲品',30),('moon-dessert','月台甜點','甜點',42))as x(slug,name,category,avg) where v.slug='beichen';
insert into public.queuehub_queue_sessions(restaurant_id,business_date,label) select r.id,current_date,'demo' from public.queuehub_restaurants r join public.queuehub_venues v on v.id=r.venue_id where v.slug='beichen';
insert into public.queuehub_queue_status(restaurant_id,queue_session_id,current_number,recent_numbers,state,source,version,updated_at) select r.id,s.id,case r.slug when'harbor-noodles'then 152 when'sunrise-bento'then 87 when'forest-curry'then 214 when'cloud-burger'then 63 when'stone-hotpot'then 118 when'field-rice'then 36 when'north-coffee'then 301 when'moon-dessert'then 74 end,case r.slug when'harbor-noodles'then array[151,150,149] when'sunrise-bento'then array[86,85,84] when'forest-curry'then array[213,212,210] when'cloud-burger'then array[62,61,60] when'stone-hotpot'then array[117,116,115] when'field-rice'then array[35,34,33] when'north-coffee'then array[300,299,298] when'moon-dessert'then array[73,72,71] end,case when r.slug='stone-hotpot'then'paused'else'open'end,case r.slug when'sunrise-bento'then'api' when'forest-curry'then'gateway' when'field-rice'then'api' when'north-coffee'then'api'else'manual'end,1,now() from public.queuehub_restaurants r join public.queuehub_venues v on v.id=r.venue_id join public.queuehub_queue_sessions s on s.restaurant_id=r.id and s.business_date=current_date and s.label='demo' where v.slug='beichen';
alter table public.queuehub_queue_status replica identity full;
do $$ begin if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='queuehub_queue_status') then alter publication supabase_realtime add table public.queuehub_queue_status; end if; end $$;
