create table if not exists public.queuehub_visitor_sessions (
  id uuid primary key default gen_random_uuid(),token_hash text not null unique,created_at timestamptz not null default now(),last_seen_at timestamptz not null default now(),expires_at timestamptz not null default (now()+interval '180 days'),revoked_at timestamptz,constraint queuehub_visitor_token_hash check (token_hash ~ '^[0-9a-f]{64}$')
);
create index if not exists queuehub_visitor_sessions_expiry_idx on public.queuehub_visitor_sessions(expires_at) where revoked_at is null;
create table if not exists public.queuehub_tracked_orders (
  id uuid primary key default gen_random_uuid(),visitor_session_id uuid not null references public.queuehub_visitor_sessions(id) on delete cascade,restaurant_id uuid not null references public.queuehub_restaurants(id) on delete cascade,queue_session_id uuid not null references public.queuehub_queue_sessions(id) on delete cascade,ticket_number integer not null check(ticket_number>0),notification_lead integer not null default 3 check(notification_lead in (1,3,5,10)),created_at timestamptz not null default now(),completed_at timestamptz,updated_at timestamptz not null default now(),unique(visitor_session_id,restaurant_id,queue_session_id,ticket_number)
);
create index if not exists queuehub_tracked_orders_visitor_active_idx on public.queuehub_tracked_orders(visitor_session_id,updated_at desc) where completed_at is null;
alter table public.queuehub_visitor_sessions enable row level security;alter table public.queuehub_tracked_orders enable row level security;revoke all on public.queuehub_visitor_sessions from anon,authenticated;revoke all on public.queuehub_tracked_orders from anon,authenticated;
create or replace function public.queuehub_create_visitor_sync_service(p_token_hash text) returns jsonb language plpgsql security definer set search_path='public' as $$declare v_id uuid;begin if p_token_hash is null or p_token_hash !~ '^[0-9a-f]{64}$' then raise exception 'invalid token hash' using errcode='22023';end if;insert into public.queuehub_visitor_sessions(token_hash) values(p_token_hash) returning id into v_id;return jsonb_build_object('ok',true,'visitor_session_id',v_id);end;$$;
create or replace function public.queuehub_sync_orders_service(p_token_hash text,p_orders jsonb default null) returns jsonb language plpgsql security definer set search_path='public' as $$declare v_session public.queuehub_visitor_sessions%rowtype;v_order jsonb;v_count integer;begin select * into v_session from public.queuehub_visitor_sessions where token_hash=p_token_hash and revoked_at is null and expires_at>now() for update;if v_session.id is null then raise exception 'visitor sync session not found' using errcode='P0002';end if;update public.queuehub_visitor_sessions set last_seen_at=now(),expires_at=greatest(expires_at,now()+interval '30 days') where id=v_session.id;if p_orders is not null then if jsonb_typeof(p_orders)<>'array' or jsonb_array_length(p_orders)>10 then raise exception 'invalid orders batch' using errcode='22023';end if;for v_order in select value from jsonb_array_elements(p_orders) loop if not exists(select 1 from public.queuehub_restaurants r join public.queuehub_queue_sessions qs on qs.restaurant_id=r.id where r.id=(v_order->>'restaurantId')::uuid and qs.id=(v_order->>'queueSessionId')::uuid) then continue;end if;insert into public.queuehub_tracked_orders(visitor_session_id,restaurant_id,queue_session_id,ticket_number,notification_lead,created_at,completed_at,updated_at) values(v_session.id,(v_order->>'restaurantId')::uuid,(v_order->>'queueSessionId')::uuid,(v_order->>'ticketNumber')::integer,case when (v_order->>'notificationLead')::integer in(1,3,5,10) then (v_order->>'notificationLead')::integer else 3 end,coalesce((v_order->>'createdAt')::timestamptz,now()),case when nullif(v_order->>'completedAt','') is null then null else (v_order->>'completedAt')::timestamptz end,now()) on conflict(visitor_session_id,restaurant_id,queue_session_id,ticket_number) do update set notification_lead=excluded.notification_lead,completed_at=excluded.completed_at,updated_at=now();end loop;end if;select count(*) into v_count from public.queuehub_tracked_orders where visitor_session_id=v_session.id;return jsonb_build_object('ok',true,'visitor_session_id',v_session.id,'orders',(select coalesce(jsonb_agg(jsonb_build_object('id',o.id,'restaurantId',o.restaurant_id,'queueSessionId',o.queue_session_id,'ticketNumber',o.ticket_number,'notificationLead',o.notification_lead,'createdAt',o.created_at,'completedAt',o.completed_at) order by o.created_at),'[]'::jsonb) from public.queuehub_tracked_orders o where o.visitor_session_id=v_session.id),'count',v_count);end;$$;
create or replace function public.queuehub_revoke_visitor_sync_service(p_token_hash text) returns boolean language plpgsql security definer set search_path='public' as $$begin update public.queuehub_visitor_sessions set revoked_at=now() where token_hash=p_token_hash and revoked_at is null;return found;end;$$;
revoke all on function public.queuehub_create_visitor_sync_service(text) from public,anon,authenticated;revoke all on function public.queuehub_sync_orders_service(text,jsonb) from public,anon,authenticated;revoke all on function public.queuehub_revoke_visitor_sync_service(text) from public,anon,authenticated;grant execute on function public.queuehub_create_visitor_sync_service(text) to service_role;grant execute on function public.queuehub_sync_orders_service(text,jsonb) to service_role;grant execute on function public.queuehub_revoke_visitor_sync_service(text) to service_role;grant select,insert,update,delete on public.queuehub_visitor_sessions to service_role;grant select,insert,update,delete on public.queuehub_tracked_orders to service_role;
