import fs from 'node:fs';import path from 'node:path';import {generateIdentity,signRequest} from './protocol.mjs';
const root=process.env.QUEUEHUB_GATEWAY_HOME||path.join(process.cwd(),'.queuehub-gateway');const cfgPath=path.join(root,'config.json'),keyPath=path.join(root,'private.pem'),outboxPath=path.join(root,'outbox.json');fs.mkdirSync(root,{recursive:true});
function readJson(p,fallback){try{return JSON.parse(fs.readFileSync(p,'utf8'))}catch{return fallback}}
function writeJson(p,v){const t=`${p}.tmp`;fs.writeFileSync(t,JSON.stringify(v,null,2));fs.renameSync(t,p)}
function config(){const c=readJson(cfgPath,null);if(!c)throw new Error(`missing ${cfgPath}; run init first`);return c}
function enqueue(payload){const q=readJson(outboxPath,[]);q.push({payload,attempts:0,nextAt:0});writeJson(outboxPath,q)}
async function sendOne(item){const c=config(),body=JSON.stringify(item.payload),privateKeyPem=fs.readFileSync(keyPath,'utf8');const headers=signRequest(privateKeyPem,body,{deviceKey:c.deviceKey,keyVersion:c.keyVersion});const r=await fetch(c.endpoint,{method:'POST',headers,body});const text=await r.text();if(!r.ok)throw new Error(`${r.status} ${text}`);return text?JSON.parse(text):{ok:true}}
async function flush(){const q=readJson(outboxPath,[]),keep=[];for(const item of q){if(item.nextAt>Date.now()){keep.push(item);continue}try{await sendOne(item)}catch(e){item.attempts=(item.attempts||0)+1;item.nextAt=Date.now()+Math.min(60000,1000*2**Math.min(item.attempts,6))+Math.floor(Math.random()*750);item.lastError=String(e.message||e).slice(0,500);keep.push(item)}}writeJson(outboxPath,keep);return{remaining:keep.length}}
function commandPayload(action,number){const c=config();return{kind:'queue',restaurantId:c.restaurantId,action,number:number??null,idempotencyKey:`gw:${c.deviceKey}:${Date.now()}:${Math.random().toString(36).slice(2,10)}`}}
async function main(){const [cmd,...args]=process.argv.slice(2);if(cmd==='init'){const id=generateIdentity();fs.writeFileSync(keyPath,id.privateKeyPem,{mode:0o600});writeJson(cfgPath,{endpoint:'https://goedzzhhvvnfczgnkqlv.supabase.co/functions/v1/queuehub-gateway-ingest',deviceKey:id.deviceKey,keyVersion:1,restaurantId:'REPLACE_RESTAURANT_UUID'});writeJson(outboxPath,[]);console.log(JSON.stringify({deviceKey:id.deviceKey,publicKeyPem:id.publicKeyPem,keyVersion:1},null,2));return}if(cmd==='queue'){const action=args[0];if(!['next','skip','toggle','set'].includes(action))throw new Error('queue action must be next|skip|toggle|set');const number=action==='set'?Number(args[1]):null;if(action==='set'&&(!Number.isInteger(number)||number<=0))throw new Error('set requires positive number');enqueue(commandPayload(action,number));console.log(await flush());return}if(cmd==='heartbeat'){enqueue({kind:'heartbeat',metadata:{agentVersion:'1.0.0',platform:process.platform,node:process.version}});console.log(await flush());return}if(cmd==='flush'){console.log(await flush());return}if(cmd==='run'){const every=Math.max(2,Number(args[0]||5))*1000;for(;;){await flush();await new Promise(r=>setTimeout(r,every))}}throw new Error('usage: node agent.mjs init|queue <next|skip|toggle|set> [number]|heartbeat|flush|run [seconds]')}
main().catch(e=>{console.error(e);process.exitCode=1});
