const QUEUEHUB_VAPID_PUBLIC_KEY='BGO8mO6RGh98OFcfaLvagYc15bGGjF0gwfvSRVfDRgl6ce0HpgWKZiRfgOf7lPsV76VxCtlWv7_W4DIn9Q7V4JA';
const QUEUEHUB_PUSH_MANAGEMENT_KEY='queuehub-push-management-v1';
function queueHubPushUuid(value){return typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)}
function queueHubPushBase64Url(bytes){let binary='';for(const b of bytes)binary+=String.fromCharCode(b);return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
function queueHubPushVapidBytes(value){const pad='='.repeat((4-value.length%4)%4);const base64=(value+pad).replace(/-/g,'+').replace(/_/g,'/');const raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
function queueHubPushManagementToken(){let token='';try{token=localStorage.getItem(QUEUEHUB_PUSH_MANAGEMENT_KEY)||''}catch{}if(/^[A-Za-z0-9_-]{32,128}$/.test(token))return token;const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);token=queueHubPushBase64Url(bytes);try{localStorage.setItem(QUEUEHUB_PUSH_MANAGEMENT_KEY,token)}catch{}return token}
const QueueHubWebPush={
  state:{status:'idle',lastError:null,lastSyncAt:0},
  supported(){return window.QueueHubClientProfile?.supportsPush??(window.isSecureContext&&'serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window)},
  async registration(){if(!this.supported())throw new Error('此瀏覽器不支援背景推播');const registration=await QueueHubServiceWorkerClient.ready();if(!registration)throw new Error('Service Worker 尚未就緒');return registration},
  async subscription({create=false}={}){const reg=await this.registration();let sub=await reg.pushManager.getSubscription();if(!sub&&create)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:queueHubPushVapidBytes(QUEUEHUB_VAPID_PUBLIC_KEY)});return sub},
  async api(body){const c=window.QueueHubRuntimeConfig?.supabase;if(!c?.url||!c?.publishableKey)throw new Error('背景推播服務尚未設定');const res=await fetch(`${String(c.url).replace(/\/$/,'')}/functions/v1/queuehub-push-subscription`,{method:'POST',headers:{apikey:c.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store',referrerPolicy:'no-referrer'});const text=await res.text();let data=null;try{data=text?JSON.parse(text):null}catch{}if(!res.ok||!data?.ok){const error=new Error(data?.error==='watch_limit'?'此裝置最多追蹤 10 張背景提醒':data?.error==='subscription_ownership'?'此裝置的推播註冊已失效，請重新開啟提醒':'背景推播同步失敗');error.code=data?.error||'push_api_error';throw error}return data},
  watchPayload(order,subscription){const r=getRestaurant(order.restaurantId);if(!r?.dbId||!queueHubPushUuid(r.dbId)||!queueHubPushUuid(order.queueSessionId))return null;return{subscription:subscription.toJSON(),managementToken:queueHubPushManagementToken(),restaurantId:r.dbId,queueSessionId:order.queueSessionId,ticketNumber:Number(order.ticketNumber),notificationLead:Number(order.notificationLead||3)}},
  async registerOrder(order,subscription=null){if(!order||order.completedAt)return false;const sub=subscription||await this.subscription();if(!sub)return false;const payload=this.watchPayload(order,sub);if(!payload)return false;await this.api({action:'register',...payload});QueueHubDiagnostics?.count('push_watch_register_success');return true},
  async removeOrder(order,subscription=null){if(!order)return false;const sub=subscription||await this.subscription();if(!sub)return false;const payload=this.watchPayload(order,sub);if(!payload)return false;await this.api({action:'remove',subscription:sub.toJSON(),managementToken:queueHubPushManagementToken(),restaurantId:payload.restaurantId,queueSessionId:payload.queueSessionId,ticketNumber:payload.ticketNumber});QueueHubDiagnostics?.count('push_watch_remove_success');return true},
  async syncActiveWatches(subscription=null){const sub=subscription||await this.subscription();if(!sub)return{registered:0,skipped:0};let registered=0,skipped=0;for(const order of activeOrders().slice(0,10)){try{if(await this.registerOrder(order,sub))registered++;else skipped++}catch(error){skipped++;QueueHubDiagnostics?.count('push_watch_register_error');console.warn('[QueueHub] push watch sync failed',error)}}this.state.lastSyncAt=Date.now();return{registered,skipped}},
  async enable(){if(!('Notification'in window))throw new Error('此瀏覽器不支援通知');const permission=await Notification.requestPermission();if(permission!=='granted')return{granted:false,background:false};QueueHubVisitorRepository.enableNotifications();if(!this.supported()){this.state.status='foreground-only';QueueHubDiagnostics?.count('push_enable_foreground_only');return{granted:true,background:false}}try{const sub=await this.subscription({create:true});if(!sub)throw new Error('無法建立 PushSubscription');await this.syncActiveWatches(sub);this.state={status:'ready',lastError:null,lastSyncAt:Date.now()};QueueHubDiagnostics?.count('push_enable_success');return{granted:true,background:true}}catch(error){this.state={status:'foreground-only',lastError:String(error?.message||error),lastSyncAt:0};QueueHubDiagnostics?.count('push_enable_fallback');console.warn('[QueueHub] background push unavailable; foreground notification remains enabled',error);return{granted:true,background:false,error}}},
  async restore(){if(!this.supported()||Notification.permission!=='granted')return false;try{const sub=await this.subscription();if(!sub)return false;QueueHubVisitorRepository.enableNotifications();await this.syncActiveWatches(sub);this.state={status:'ready',lastError:null,lastSyncAt:Date.now()};QueueHubDiagnostics?.count('push_restore_success');return true}catch(error){this.state={status:'restore-error',lastError:String(error?.message||error),lastSyncAt:0};QueueHubDiagnostics?.count('push_restore_error');console.warn('[QueueHub] push restore failed',error);return false}}
};
window.QueueHubWebPush=QueueHubWebPush;
