const STORAGE='queuehub-v3';
const CHANNEL='queuehub-v3';
const channel='BroadcastChannel' in window?new BroadcastChannel(CHANNEL):null;
const venue={id:'beichen',name:'北辰休息站（Demo）',location:'示範場域',capacityTarget:3000};
const seed=[
{id:'harbor-noodles',name:'港町麵屋',category:'麵食',aliases:['拉麵','麵','noodle'],current:152,recent:[151,150,149],status:'open',avg:45,updated:Date.now()-22000,integration:'manual'},
{id:'sunrise-bento',name:'日光便當',category:'便當',aliases:['便當','飯盒','bento'],current:87,recent:[86,85,84],status:'open',avg:50,updated:Date.now()-38000,integration:'api'},
{id:'forest-curry',name:'森野咖哩',category:'飯類',aliases:['咖哩','curry'],current:214,recent:[213,212,210],status:'open',avg:55,updated:Date.now()-19000,integration:'gateway'},
{id:'cloud-burger',name:'雲朵漢堡',category:'速食',aliases:['漢堡','burger','薯條'],current:63,recent:[62,61,60],status:'open',avg:38,updated:Date.now()-12000,integration:'manual'},
{id:'stone-hotpot',name:'石庭小鍋',category:'鍋物',aliases:['火鍋','鍋','hotpot'],current:118,recent:[117,116,115],status:'paused',avg:65,updated:Date.now()-145000,integration:'manual'},
{id:'field-rice',name:'田野食堂',category:'飯類',aliases:['飯','丼飯','rice'],current:36,recent:[35,34,33],status:'open',avg:48,updated:Date.now()-27000,integration:'api'},
{id:'north-coffee',name:'北辰咖啡',category:'飲品',aliases:['咖啡','飲料','coffee'],current:301,recent:[300,299,298],status:'open',avg:30,updated:Date.now()-9000,integration:'api'},
{id:'moon-dessert',name:'月台甜點',category:'甜點',aliases:['甜點','蛋糕','dessert'],current:74,recent:[73,72,71],status:'open',avg:42,updated:Date.now()-51000,integration:'manual'}
];
let selectedAdmin=seed[0].id;
let search={query:'',category:'全部',openOnly:false,sortBy:'relevance'};
function defaultState(){return{restaurants:seed,orders:[],events:[],visitor:{id:'qh_'+cryptoRandom(),createdAt:new Date().toISOString(),lastSeenAt:new Date().toISOString(),lastRoute:'/'},integrations:{}}}
function cryptoRandom(){try{return crypto.getRandomValues(new Uint32Array(2)).join('')}catch(e){return Math.random().toString(36).slice(2)}}
function load(){try{const s=JSON.parse(localStorage.getItem(STORAGE));if(s?.restaurants&&s?.visitor){s.orders=s.orders||[];s.events=s.events||[];s.integrations=s.integrations||{};return s}}catch(e){}return defaultState()}
let state=load();
function persist(){state.visitor.lastSeenAt=new Date().toISOString();localStorage.setItem(STORAGE,JSON.stringify(state));channel?.postMessage({type:'state',state})}
channel?.addEventListener('message',e=>{if(e.data?.type==='state'){state=e.data.state;render()}});
function path(){return location.hash.replace(/^#/,'')||'/'}
function go(p){location.hash=p}
window.go=go;
function routeBase(){return path().split('?')[0]}
window.addEventListener('hashchange',()=>{state.visitor.lastRoute=path();persist();render()});
function fmtAgo(ts){const s=Math.max(0,Math.floor((Date.now()-ts)/1000));if(s<60)return `${s} 秒前`;if(s<3600)return `${Math.floor(s/60)} 分鐘前`;return `${Math.floor(s/3600)} 小時前`}
function estimate(r,ahead=8){return Math.max(1,Math.ceil(ahead*r.avg/60))}
function statusText(r){return r.status==='open'?'叫號中':r.status==='paused'?'暫停':'已結束'}
function esc(s=''){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function nav(){document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',routeBase()===b.dataset.nav||(b.dataset.nav==='/my-orders'&&routeBase().startsWith('/my-orders'))))}
function restaurantCard(r){return `<article class="card restaurant" onclick="go('/restaurant/${r.id}')"><div class="row between"><div><div class="name">${r.name}</div><div class="queueLabel">${r.category}</div></div><span class="tag ${r.status==='open'?'ok':'pause'}">${statusText(r)}</span></div><div class="queueNo">${r.current}</div><div class="queueLabel">目前叫到</div><div class="recent">${r.recent.slice(0,3).map(n=>`<span>${n}</span>`).join('')}</div><div class="meta"><span>估計每號 ${r.avg} 秒</span><span>${fmtAgo(r.updated)}更新</span></div></article>`}
function filteredRestaurants(){const q=search.query.trim().toLowerCase();let rs=state.restaurants.filter(r=>{const hay=[r.name,r.category,...(r.aliases||[])].join(' ').toLowerCase();return(!q||hay.includes(q))&&(search.category==='全部'||r.category===search.category)&&(!search.openOnly||r.status==='open')});if(search.sortBy==='wait')rs.sort((a,b)=>a.avg-b.avg);if(search.sortBy==='name')rs.sort((a,b)=>a.name.localeCompare(b.name,'zh-Hant'));if(search.sortBy==='relevance'&&q)rs.sort((a,b)=>Number(!a.name.toLowerCase().includes(q))-Number(!b.name.toLowerCase().includes(q)));return rs}
function renderHome(){const cats=['全部',...new Set(state.restaurants.map(r=>r.category))];const rs=filteredRestaurants();return `<section class="hero"><div class="panel heroMain"><div class="eyebrow">VENUE-WIDE QUEUE · ${venue.name}</div><h1>不用擠在店門口，<br>也知道叫到幾號。</h1><div class="lead">掃一次 QR，就能集中追蹤休息站內不同餐廳的叫號。搜尋餐廳、看目前號碼，之後可把多張取餐單加入「我的取餐」。</div><div class="actions"><button class="btn primary" onclick="go('/my-orders')">查看我的取餐</button><button class="btn" onclick="go('/board')">公共叫號看板</button></div></div><aside class="panel heroStats"><div class="stat"><span>示範餐廳</span><strong>${state.restaurants.length}</strong></div><div class="stat"><span>目前叫號中</span><strong>${state.restaurants.filter(r=>r.status==='open').length}</strong></div><div class="stat"><span>設計同時使用</span><strong>3,000</strong></div></aside></section><div class="notice">目前是產品 Prototype：同一裝置可即時同步；正式跨裝置 3,000 人版需接 Realtime backend / POS API。</div><section class="searchDock"><div class="searchBox"><div class="searchRow"><div class="searchIcon">⌕</div><input id="searchInput" class="searchInput" autocomplete="off" inputmode="search" placeholder="搜尋餐廳、料理，例如：咖哩、漢堡、咖啡" value="${esc(search.query)}" oninput="setSearch(this.value)">${search.query?`<button class="clearBtn" aria-label="清除搜尋" onclick="clearSearch()">×</button>`:''}</div><div class="filters">${cats.map(c=>`<button class="chip ${search.category===c?'active':''}" onclick="setCategory('${c}')">${c}</button>`).join('')}<button class="chip ${search.openOnly?'active':''}" onclick="toggleOpen()">只看叫號中</button><select class="select" onchange="setSort(this.value)"><option value="relevance" ${search.sortBy==='relevance'?'selected':''}>最相關</option><option value="wait" ${search.sortBy==='wait'?'selected':''}>處理速度</option><option value="name" ${search.sortBy==='name'?'selected':''}>店名</option></select></div></div></section><div class="sectionHead"><h2>${search.query?'搜尋結果':'所有餐廳'}</h2><span>${rs.length} 家符合</span></div>${rs.length?`<section class="grid">${rs.map(restaurantCard).join('')}</section>`:`<div class="panel empty"><strong>找不到符合的餐廳</strong>試試「咖哩」、「飯」、「飲料」，或清除篩選條件。<div style="margin-top:12px"><button class="btn" onclick="resetFilters()">清除所有篩選</button></div></div>`}`}
window.setSearch=v=>{search.query=v;renderHomeOnly()};window.clearSearch=()=>{search.query='';render()};window.setCategory=c=>{search.category=c;render()};window.toggleOpen=()=>{search.openOnly=!search.openOnly;render()};window.setSort=v=>{search.sortBy=v;render()};window.resetFilters=()=>{search={query:'',category:'全部',openOnly:false,sortBy:'relevance'};render()};
function renderHomeOnly(){const app=document.getElementById('app');app.innerHTML=renderHome();nav();const i=document.getElementById('searchInput');i?.focus();if(i)i.setSelectionRange(i.value.length,i.value.length)}
function getRestaurant(id){return state.restaurants.find(r=>r.id===id)}
function renderRestaurant(id){const r=getRestaurant(id);if(!r)return `<div class="panel empty"><strong>找不到餐廳</strong><button class="btn" onclick="go('/')">回總覽</button></div>`;return `<div class="pageHead"><button class="back" onclick="history.back()">←</button><div><h2>${r.name}</h2><div class="muted">${r.category} · ${statusText(r)}</div></div></div><section class="detail"><div class="panel bigStatus"><h2>目前叫到</h2><div class="bigNo">${r.current}</div><div class="muted">最近：${r.recent.join(' · ')} · ${fmtAgo(r.updated)}更新</div></div><div class="panel ticketPanel"><h3>我的取餐號碼</h3><p class="muted">輸入號碼即可估算前面還有幾組。下一階段會把它加入多餐廳追蹤。</p><div class="field"><input id="ticket" inputmode="numeric" placeholder="例如 168"><button class="btn primary" onclick="previewTicket('${r.id}')">查看</button></div><div id="ticketResult"></div></div></section>`}
window.previewTicket=id=>{const r=getRestaurant(id);const input=document.getElementById('ticket');const n=Number(input?.value);const box=document.getElementById('ticketResult');if(!Number.isFinite(n)||n<=0){box.innerHTML='<div class="result warn">請輸入有效的取餐號碼。</div>';return}const d=n-r.current;if(d<0)box.innerHTML=`<div class="result danger"><strong>可能已過號</strong>目前 ${r.current}，你是 ${n}。請直接洽店家確認。</div>`;else if(d===0)box.innerHTML=`<div class="result"><strong>就是現在</strong>目前正在叫 ${n}，建議前往櫃台。</div>`;else box.innerHTML=`<div class="result"><strong>前面約 ${d} 組</strong>估計約 ${estimate(r,d)} 分鐘；此時間為示意估算。</div>`}
function renderBoard(){return `<section class="board"><div class="row between" style="margin-bottom:15px"><div><div class="eyebrow" style="color:#9ab4ff">PUBLIC BOARD</div><h2 style="margin:4px 0">${venue.name}</h2></div><button class="btn" onclick="go('/')">離開看板</button></div><div class="boardGrid">${state.restaurants.map(r=>`<div class="boardCard"><div><div class="bname">${r.name}</div><small>${r.category} · ${statusText(r)}</small></div><div class="bn">${r.current}</div><small>${fmtAgo(r.updated)}更新</small></div>`).join('')}</div></section>`}
function placeholder(title,desc){return `<div class="panel empty"><strong>${title}</strong>${desc}</div>`}
function render(){let p=routeBase();let html;if(p==='/')html=renderHome();else if(p.startsWith('/restaurant/'))html=renderRestaurant(p.split('/')[2]);else if(p==='/board')html=renderBoard();else if(p==='/my-orders')html=placeholder('我的取餐正在建立','下一階段會加入多餐廳同時追蹤、自動排序與回復。');else if(p==='/admin')html=placeholder('店家後台正在建立','將提供 +1、跳號、暫停、直接輸入號碼與事件紀錄。');else if(p==='/integrations')html=placeholder('系統整合正在建立','將提供 API / Webhook、平板手動與 Local Gateway 三種模式。');else html=placeholder('找不到頁面','請回到首頁。');document.getElementById('app').innerHTML=html;nav()}
window.addEventListener('DOMContentLoaded',()=>{if(!location.hash){const active=state.orders?.filter(o=>!o.completedAt)||[];if(active.length===1)location.hash=`/restaurant/${active[0].restaurantId}`;else if(active.length>1)location.hash='/my-orders';else location.hash=state.visitor.lastRoute||'/'}render()});
