const STORAGE='queuehub-v3';
const CHANNEL='queuehub-v3';
const channel='BroadcastChannel' in window?new BroadcastChannel(CHANNEL):null;
const venue={id:'beichen',name:'北辰休息站（Demo）',location:'示範場域',capacityTarget:3000};
const seed=[
{id:'harbor-noodles',name:'港町麵屋',category:'麵食',aliases:['拉麵','麵','noodle'],current:152,recent:[151,150,149],status:'open',avg:45,updated:Date.now()-22000,integration:'manual'},
{id:'sunrise-bento',name:'日光便當',category:'便當',aliases:['便當','飯盒','bento'],current:87,recent:[86,85,84],status:'open',avg:50,updated:Date.now()-38000,integration:'api'},
{id:'forest-curry',name:'森野咖哩',category:'飯類',aliases:['咖哩','curry'],current:214,recent:[213,212,210],status:'open',avg:55,updated:Date.now()-19000,integration:'gateway'},
{id:'cloud-burger',name:'雲朵漢堡',category:'速食',aliases:['漢堡','burger','薯條'],current:63,recent:[62,61,60],status:'open',avg:38,updated:Date.now()-12000,integration:'manual'},
{id:'stone-hotpot',name:'石庭小鍋',category:'鍋物',aliases:['火鍋','鍋','hotpot'],current:118,recent:[117,116,115],status:'paused',avg:65,updated:Date.now()-145000,integration:'manual'},
{id:'field-rice',name:'田野食堂',category:'飯類',aliases:['飯','丼飯','rice'],current:36,recent:[35,34,33],status:'open',avg:48,updated:Date.now()-27000,integration:'api'},
{id:'north-coffee',name:'北辰咖啡',category:'飲品',aliases:['咖啡','飲料','coffee'],current:301,recent:[300,299,298],status:'open',avg:30,updated:Date.now()-9000,integration:'api'},
{id:'moon-dessert',name:'月台甜點',category:'甜點',aliases:['甜點','蛋糕','dessert'],current:74,recent:[73,72,71],status:'open',avg:42,updated:Date.now()-51000,integration:'manual'}
];
let selectedAdmin=seed[0].id;
let search={query:'',category:'全部',openOnly:false,sortBy:'relevance'};
function cryptoRandom(){try{return crypto.getRandomValues(new Uint32Array(2)).join('')}catch(e){return Math.random().toString(36).slice(2)}}
function defaultState(){return{restaurants:seed,orders:[],events:[],visitor:{id:'qh_'+cryptoRandom(),createdAt:new Date().toISOString(),lastSeenAt:new Date().toISOString(),lastRoute:'/'},integrations:{}}}
function load(){try{const s=JSON.parse(localStorage.getItem(STORAGE));if(s?.restaurants&&s?.visitor){s.orders=s.orders||[];s.events=s.events||[];s.integrations=s.integrations||{};return s}}catch(e){}return defaultState()}
let state=load();
function persist(){state.visitor.lastSeenAt=new Date().toISOString();localStorage.setItem(STORAGE,JSON.stringify(state));channel?.postMessage({type:'state',state})}
channel?.addEventListener('message',e=>{if(e.data?.type==='state'){state=e.data.state;render()}});
function path(){return location.hash.replace(/^#/,'')||'/'}
function routeBase(){return path().split('?')[0]}
function go(p){location.hash=p}
window.go=go;
window.addEventListener('hashchange',()=>{state.visitor.lastRoute=path();persist();render()});
function fmtAgo(ts){const s=Math.max(0,Math.floor((Date.now()-ts)/1000));if(s<60)return `${s} 秒前`;if(s<3600)return `${Math.floor(s/60)} 分鐘前`;return `${Math.floor(s/3600)} 小時前`}
function estimate(r,ahead=8){return Math.max(1,Math.ceil(Math.max(0,ahead)*r.avg/60))}
function statusText(r){return r.status==='open'?'叫號中':r.status==='paused'?'暫停':'已結束'}
function esc(s=''){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function toast(msg){document.querySelector('.toast')?.remove();const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2400)}
function nav(){const base=routeBase();document.querySelectorAll('[data-nav]').forEach(b=>{const hit=base===b.dataset.nav||(b.dataset.nav==='/my-orders'&&base.startsWith('/my-orders'));b.classList.toggle('active',hit)});const n=activeOrders().length;document.querySelectorAll('[data-nav="/my-orders"]').forEach(b=>b.title=n?`${n} 張進行中取餐單`:'目前沒有取餐單')}
function restaurantCard(r){return `<article class="card restaurant" onclick="go('/restaurant/${r.id}')"><div class="row between"><div><div class="name">${r.name}</div><div class="queueLabel">${r.category}</div></div><span class="tag ${r.status==='open'?'ok':'pause'}">${statusText(r)}</span></div><div class="queueNo">${r.current}</div><div class="queueLabel">目前叫到</div><div class="recent">${r.recent.slice(0,3).map(n=>`<span>${n}</span>`).join('')}</div><div class="meta"><span>估計每號 ${r.avg} 秒</span><span>${fmtAgo(r.updated)}更新</span></div></article>`}
function filteredRestaurants(){const q=search.query.trim().toLowerCase();let rs=state.restaurants.filter(r=>{const hay=[r.name,r.category,...(r.aliases||[])].join(' ').toLowerCase();return(!q||hay.includes(q))&&(search.category==='全部'||r.category===search.category)&&(!search.openOnly||r.status==='open')});if(search.sortBy==='wait')rs.sort((a,b)=>a.avg-b.avg);if(search.sortBy==='name')rs.sort((a,b)=>a.name.localeCompare(b.name,'zh-Hant'));if(search.sortBy==='relevance'&&q)rs.sort((a,b)=>Number(!a.name.toLowerCase().includes(q))-Number(!b.name.toLowerCase().includes(q)));return rs}
function renderHome(){const cats=['全部',...new Set(state.restaurants.map(r=>r.category))];const rs=filteredRestaurants();const n=activeOrders().length;return `<section class="hero"><div class="panel heroMain"><div class="eyebrow">VENUE-WIDE QUEUE · ${venue.name}</div><h1>不用擠在店門口，<br>也知道叫到幾號。</h1><div class="lead">掃一次 QR，就能集中追蹤休息站內不同餐廳的叫號。搜尋餐廳、看目前號碼，把多張取餐單加入「我的取餐」。</div><div class="actions"><button class="btn primary" onclick="go('/my-orders')">我的取餐${n?` · ${n} 張`:''}</button><button class="btn" onclick="go('/board')">公共叫號看板</button></div></div><aside class="panel heroStats"><div class="stat"><span>示範餐廳</span><strong>${state.restaurants.length}</strong></div><div class="stat"><span>目前叫號中</span><strong>${state.restaurants.filter(r=>r.status==='open').length}</strong></div><div class="stat"><span>設計同時使用</span><strong>3,000</strong></div></aside></section><div class="notice">目前是產品 Prototype：同一裝置可即時同步；正式跨裝置 3,000 人版需接 Realtime backend / POS API。</div><section class="searchDock"><div class="searchBox"><div class="searchRow"><div class="searchIcon">⌕</div><input id="searchInput" class="searchInput" autocomplete="off" inputmode="search" placeholder="搜尋餐廳、料理，例如：咖哩、漢堡、咖啡" value="${esc(search.query)}" oninput="setSearch(this.value)">${search.query?`<button class="clearBtn" aria-label="清除搜尋" onclick="clearSearch()">×</button>`:''}</div><div class="filters">${cats.map(c=>`<button class="chip ${search.category===c?'active':''}" onclick="setCategory('${c}')">${c}</button>`).join('')}<button class="chip ${search.openOnly?'active':''}" onclick="toggleOpen()">只看叫號中</button><select class="select" onchange="setSort(this.value)"><option value="relevance" ${search.sortBy==='relevance'?'selected':''}>最相關</option><option value="wait" ${search.sortBy==='wait'?'selected':''}>處理速度</option><option value="name" ${search.sortBy==='name'?'selected':''}>店名</option></select></div></div></section><div class="sectionHead"><h2>${search.query?'搜尋結果':'所有餐廳'}</h2><span>${rs.length} 家符合</span></div>${rs.length?`<section class="grid">${rs.map(restaurantCard).join('')}</section>`:`<div class="panel empty"><strong>找不到符合的餐廳</strong>試試「咖哩」、「飯」、「飲料」，或清除篩選條件。<div style="margin-top:12px"><button class="btn" onclick="resetFilters()">清除所有篩選</button></div></div>`}`}
window.setSearch=v=>{search.query=v;renderHomeOnly()};window.clearSearch=()=>{search.query='';render()};window.setCategory=c=>{search.category=c;render()};window.toggleOpen=()=>{search.openOnly=!search.openOnly;render()};window.setSort=v=>{search.sortBy=v;render()};window.resetFilters=()=>{search={query:'',category:'全部',openOnly:false,sortBy:'relevance'};render()};
function renderHomeOnly(){const app=document.getElementById('app');app.innerHTML=renderHome();nav();const i=document.getElementById('searchInput');i?.focus();if(i)i.setSelectionRange(i.value.length,i.value.length)}
function getRestaurant(id){return state.restaurants.find(r=>r.id===id)}
function activeOrders(){return state.orders.filter(o=>!o.completedAt)}
function orderStatus(order){const r=getRestaurant(order.restaurantId);if(!r)return{diff:999,label:'資料異常',cls:'waiting',estimate:0,rank:99};const diff=order.ticketNumber-r.current;if(diff<0)return{diff,label:'可能已過號',cls:'soon',estimate:0,rank:0};if(diff===0)return{diff,label:'正在叫你的號碼',cls:'soon',estimate:0,rank:1};if(diff<=order.notificationLead)return{diff,label:`快到了 · 剩約 ${diff} 組`,cls:'soon',estimate:estimate(r,diff),rank:2};return{diff,label:`等待中 · 前面約 ${diff} 組`,cls:'waiting',estimate:estimate(r,diff),rank:3}}
function currentQueueSession(r){return `${new Date().toISOString().slice(0,10).replaceAll('-','')}-${r.id}-demo`}
function renderRestaurant(id){const r=getRestaurant(id);if(!r)return `<div class="panel empty"><strong>找不到餐廳</strong><button class="btn" onclick="go('/')">回總覽</button></div>`;const mine=activeOrders().filter(o=>o.restaurantId===id);return `<div class="pageHead"><button class="back" onclick="history.back()">←</button><div><h2>${r.name}</h2><div class="muted">${r.category} · ${statusText(r)}</div></div></div><section class="detail"><div class="panel bigStatus"><h2>目前叫到</h2><div class="bigNo">${r.current}</div><div class="muted">最近：${r.recent.join(' · ')} · ${fmtAgo(r.updated)}更新</div>${mine.length?`<div class="notice" style="margin-bottom:0">你正在追蹤這家店的 ${mine.length} 張取餐單。</div>`:''}</div><div class="panel ticketPanel"><h3>加入我的取餐</h3><p class="muted">輸入你的取餐號碼。可以同時追蹤不同餐廳，系統會依「哪張快到」自動排序。</p><div class="field"><input id="ticket" inputmode="numeric" placeholder="例如 168"><button class="btn primary" onclick="previewTicket('${r.id}')">查看</button></div><div id="ticketResult"></div></div></section>`}
window.previewTicket=id=>{const r=getRestaurant(id);const input=document.getElementById('ticket');const n=Number(input?.value);const box=document.getElementById('ticketResult');if(!Number.isFinite(n)||n<=0){box.innerHTML='<div class="result warn">請輸入有效的取餐號碼。</div>';return}const d=n-r.current;if(d<0)box.innerHTML=`<div class="result danger"><strong>可能已過號</strong>目前 ${r.current}，你是 ${n}。請直接洽店家確認。<div style="margin-top:10px"><button class="btn" onclick="trackOrder('${id}',${n})">仍要加入追蹤</button></div></div>`;else if(d===0)box.innerHTML=`<div class="result"><strong>就是現在</strong>目前正在叫 ${n}，建議前往櫃台。<div style="margin-top:10px"><button class="btn primary" onclick="trackOrder('${id}',${n})">加入我的取餐</button></div></div>`;else box.innerHTML=`<div class="result"><strong>前面約 ${d} 組</strong>估計約 ${estimate(r,d)} 分鐘；此時間為示意估算。<div class="formGrid" style="margin-bottom:0"><label>提前幾組提醒<select id="lead" class="input"><option value="1">1 組</option><option value="3" selected>3 組</option><option value="5">5 組</option><option value="10">10 組</option></select></label><div style="display:flex;align-items:end"><button class="btn primary" style="width:100%" onclick="trackOrder('${id}',${n})">加入我的取餐</button></div></div></div>`}
window.trackOrder=(restaurantId,ticketNumber)=>{const r=getRestaurant(restaurantId);if(!r)return;const active=activeOrders();if(active.length>=10){toast('最多同時追蹤 10 張取餐單');return}const queueSessionId=currentQueueSession(r);if(active.some(o=>o.restaurantId===restaurantId&&o.queueSessionId===queueSessionId&&o.ticketNumber===ticketNumber)){toast('這張取餐單已經在追蹤中');go('/my-orders');return}const lead=Number(document.getElementById('lead')?.value||3);state.orders.push({id:'ord_'+cryptoRandom(),visitorSessionId:state.visitor.id,restaurantId,queueSessionId,ticketNumber,notificationLead:[1,3,5,10].includes(lead)?lead:3,notificationsEnabled:false,createdAt:new Date().toISOString(),completedAt:null});persist();toast(`${r.name} #${ticketNumber} 已加入我的取餐`);go('/my-orders')}
window.completeOrder=id=>{const o=state.orders.find(x=>x.id===id);if(!o)return;o.completedAt=new Date().toISOString();persist();toast('已標記完成');render()};
window.removeOrder=id=>{const i=state.orders.findIndex(x=>x.id===id);if(i<0)return;state.orders.splice(i,1);persist();toast('已移除取餐單');render()};
function renderMyOrders(){const orders=activeOrders().map(o=>({o,r:getRestaurant(o.restaurantId),s:orderStatus(o)})).filter(x=>x.r).sort((a,b)=>a.s.rank-b.s.rank||a.s.diff-b.s.diff);if(!orders.length)return `<div class="pageHead"><div><h2>我的取餐</h2><div class="muted">同時追蹤多家餐廳，不用來回盯螢幕。</div></div></div><div class="panel empty"><strong>目前沒有進行中的取餐單</strong>到餐廳頁輸入取餐號碼，或之後直接掃收據 QR 即可加入。<div style="margin-top:14px"><button class="btn primary" onclick="go('/')">搜尋餐廳</button></div></div>`;const first=orders[0];return `<div class="pageHead"><div><h2>我的取餐</h2><div class="muted">${orders.length} 張進行中 · 系統依快到程度排序</div></div></div><div class="notice"><strong>建議先注意：${first.r.name} #${first.o.ticketNumber}</strong><br>${first.s.label}${first.s.estimate?`，估計約 ${first.s.estimate} 分鐘`:''}。</div><section class="orders">${orders.map(({o,r,s})=>`<article class="panel order"><div><div class="orderUrgency ${s.cls}">${s.label}</div><div class="orderTitle">${r.name}</div><div class="orderNums"><div>目前<b>${r.current}</b></div><div>我的號碼<b>${o.ticketNumber}</b></div><div>預估<b>${s.estimate?`${s.estimate}m`:'—'}</b></div></div><div class="muted" style="font-size:11px;margin-top:8px">提醒設定：提前 ${o.notificationLead} 組 · ${fmtAgo(r.updated)}更新</div></div><div class="orderRight"><div class="countdown">${s.diff>0?s.diff:0}<span style="font-size:11px;color:var(--muted)"> 組</span></div><div class="actions" style="justify-content:flex-end;margin-top:8px"><button class="btn" onclick="go('/restaurant/${r.id}')">查看</button><button class="btn" onclick="completeOrder('${o.id}')">已取餐</button><button class="btn ghost" onclick="removeOrder('${o.id}')">移除</button></div></div></article>`).join('')}</section><div class="panel" style="margin-top:14px;padding:18px"><div class="row between"><div><strong>還有其他餐廳？</strong><div class="muted" style="font-size:12px">最多同時追蹤 10 張訂單。</div></div><button class="btn primary" onclick="go('/')">再加入一張</button></div></div>`}
function renderBoard(){return `<section class="board"><div class="row between" style="margin-bottom:15px"><div><div class="eyebrow" style="color:#9ab4ff">PUBLIC BOARD</div><h2 style="margin:4px 0">${venue.name}</h2></div><button class="btn" onclick="go('/')">離開看板</button></div><div class="boardGrid">${state.restaurants.map(r=>`<div class="boardCard"><div><div class="bname">${r.name}</div><small>${r.category} · ${statusText(r)}</small></div><div class="bn">${r.current}</div><small>${fmtAgo(r.updated)}更新</small></div>`).join('')}</div></section>`}
function placeholder(title,desc){return `<div class="panel empty"><strong>${title}</strong>${desc}</div>`}
function render(){let p=routeBase();let html;if(p==='/')html=renderHome();else if(p.startsWith('/restaurant/'))html=renderRestaurant(p.split('/')[2]);else if(p==='/board')html=renderBoard();else if(p==='/my-orders')html=renderMyOrders();else if(p==='/admin')html=placeholder('店家後台正在建立','下一階段將提供 +1、跳號、暫停、直接輸入號碼與事件紀錄。');else if(p==='/integrations')html=placeholder('系統整合正在建立','下一階段將提供 API / Webhook、平板手動與 Local Gateway 三種模式。');else html=placeholder('找不到頁面','請回到首頁。');document.getElementById('app').innerHTML=html;nav()}
window.addEventListener('DOMContentLoaded',()=>{if(!location.hash){const active=activeOrders();if(active.length===1)location.hash=`/restaurant/${active[0].restaurantId}`;else if(active.length>1)location.hash='/my-orders';else location.hash=state.visitor.lastRoute||'/'}render()});
