const coreRender=render;
function addEvent(restaurant,type,number){state.events.unshift({id:'evt_'+cryptoRandom(),restaurantId:restaurant.id,queueSessionId:currentQueueSession(restaurant),type,number,occurredAt:new Date().toISOString(),source:restaurant.integration||'manual'});state.events=state.events.slice(0,80)}
function mutateQueue(id,mutator,eventType,number){const r=getRestaurant(id);if(!r)return;const previous=JSON.parse(JSON.stringify(state));mutator(r);r.updated=Date.now();addEvent(r,eventType,number);persist();checkNotificationTransitions(previous,state);render()}
window.adminNext=id=>mutateQueue(id,r=>{r.recent=[r.current,...r.recent].slice(0,3);r.current+=1;r.status='open'},'called',getRestaurant(id)?.current+1);
window.adminSkip=id=>mutateQueue(id,r=>{r.recent=[r.current,...r.recent].slice(0,3);r.current+=2;r.status='open'},'skipped',getRestaurant(id)?.current+1);
window.adminToggle=id=>{const r=getRestaurant(id);const next=r.status==='paused'?'open':'paused';mutateQueue(id,x=>x.status=next,next==='open'?'resumed':'paused',r.current)};
window.adminSet=id=>{const n=Number(document.getElementById('adminSetNumber')?.value);if(!Number.isFinite(n)||n<=0){toast('請輸入有效號碼');return}mutateQueue(id,r=>{r.recent=[r.current,...r.recent].slice(0,3);r.current=n;r.status='open'},'called',n)};
window.pickAdmin=id=>{selectedAdmin=id;render()};
function eventLabel(e){return({called:'叫號',skipped:'跳號',paused:'暫停',resumed:'恢復',reset:'重設'})[e.type]||e.type}
function baseUrl(){return location.href.split('#')[0]}
function qrLink(type,r,ticket){if(type==='venue')return `${baseUrl()}#/`;if(type==='restaurant')return `${baseUrl()}#/restaurant/${r.id}`;const session=currentQueueSession(r);const token='demo_'+cryptoRandom().slice(0,10);return `${baseUrl()}#/restaurant/${r.id}?ticket=${encodeURIComponent(ticket)}&session=${encodeURIComponent(session)}&token=${encodeURIComponent(token)}`}
window.updateQrPreview=()=>{const r=getRestaurant(selectedAdmin);if(!r)return;const type=document.getElementById('qrType')?.value||'restaurant';const ticket=Number(document.getElementById('qrTicket')?.value)||168;const url=qrLink(type,r,ticket);const out=document.getElementById('qrUrl');if(out)out.textContent=url;const canvas=document.getElementById('qrCanvas');if(canvas&&window.QRCode?.toCanvas){QRCode.toCanvas(canvas,url,{width:190,margin:1,errorCorrectionLevel:'M'},err=>{if(err)console.warn(err)})}}
window.copyQrUrl=async()=>{const text=document.getElementById('qrUrl')?.textContent||'';try{await navigator.clipboard.writeText(text);toast('QR 連結已複製')}catch(e){toast('無法存取剪貼簿')}};
function renderAdmin(){const r=getRestaurant(selectedAdmin)||state.restaurants[0];selectedAdmin=r.id;const events=state.events.filter(e=>e.restaurantId===r.id).slice(0,12);return `<div class="pageHead"><div><h2>店家叫號後台</h2><div class="muted">Demo 操作會即時同步到同瀏覽器其他分頁；正式版需驗證與權限控管。</div></div></div><section class="admin"><aside class="panel adminList"><h3 style="margin-top:0">選擇餐廳</h3>${state.restaurants.map(x=>`<button class="${x.id===r.id?'active':''}" onclick="pickAdmin('${x.id}')"><strong>${x.name}</strong><br><span class="muted">目前 ${x.current} · ${statusText(x)}</span></button>`).join('')}</aside><div style="display:grid;gap:14px"><section class="panel adminMain"><div class="row between"><div><div class="muted">${r.category}</div><h2 style="margin:3px 0">${r.name}</h2></div><span class="tag ${r.status==='open'?'ok':'pause'}">${statusText(r)}</span></div><div class="adminNo">${r.current}</div><div class="actions"><button class="btn primary" onclick="adminNext('${r.id}')">+1 叫下一號</button><button class="btn" onclick="adminSkip('${r.id}')">跳過一號</button><button class="btn warn" onclick="adminToggle('${r.id}')">${r.status==='paused'?'恢復叫號':'暫停叫號'}</button></div><div class="formGrid"><input id="adminSetNumber" class="input" inputmode="numeric" placeholder="直接輸入號碼"><button class="btn" onclick="adminSet('${r.id}')">設定目前號碼</button></div><div class="notice" style="margin-bottom:0">後台每次變更會產生 QueueEvent；其他分頁收到更新後，若跨過使用者設定的提醒門檻，就會觸發通知流程。</div></section><section class="panel adminMain"><div class="row between"><div><h3 style="margin:0">QR Code 產生器</h3><div class="muted" style="font-size:12px">入口 QR、餐廳 QR、收據專屬 QR。</div></div><button class="btn" onclick="copyQrUrl()">複製連結</button></div><div class="formGrid"><select id="qrType" class="input" onchange="updateQrPreview()"><option value="restaurant">餐廳 QR</option><option value="venue">休息站總覽 QR</option><option value="order">取餐單專屬 QR</option></select><input id="qrTicket" class="input" inputmode="numeric" value="168" oninput="updateQrPreview()" placeholder="取餐號碼"></div><div class="qrGrid"><div class="qrBox"><canvas id="qrCanvas" width="190" height="190"></canvas></div><div><strong>掃描後目的地</strong><div id="qrUrl" class="code" style="margin-top:8px"></div><p class="muted" style="font-size:12px">正式 POS 版本會由後端產生不可猜測的 order token，不會把姓名、電話等個資放進 QR。</p></div></div></section><section class="panel adminMain"><h3 style="margin-top:0">事件紀錄</h3>${events.length?events.map(e=>`<div class="event"><span>${new Date(e.occurredAt).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}</span><strong>${eventLabel(e)}${e.number?` #${e.number}`:''}</strong><span>${e.source}</span></div>`).join(''):`<div class="muted">尚無操作紀錄。</div>`}</section></div></section>`}
function integrationDefault(r){return state.integrations[r.id]||{type:r.integration||'manual',enabled:true,apiEndpoint:'',webhookUrl:'',pollingIntervalSeconds:5,apiKeySecretName:'',gatewayDeviceId:''}}
window.saveIntegration=id=>{const r=getRestaurant(id);if(!r)return;const cfg={type:document.getElementById('intType').value,enabled:document.getElementById('intEnabled').checked,apiEndpoint:document.getElementById('apiEndpoint').value.trim(),webhookUrl:document.getElementById('webhookUrl').value.trim(),pollingIntervalSeconds:Math.max(1,Number(document.getElementById('polling').value)||5),apiKeySecretName:document.getElementById('secretName').value.trim(),gatewayDeviceId:document.getElementById('gatewayId').value.trim()};state.integrations[id]=cfg;r.integration=cfg.type;persist();toast('整合設定已儲存（Demo）');render()};
function renderIntegrations(){const r=getRestaurant(selectedAdmin)||state.restaurants[0];const c=integrationDefault(r);return `<div class="pageHead"><div><h2>系統整合</h2><div class="muted">不同廠牌叫號機最後都正規化成同一個 QueueStatus / QueueEvent。</div></div></div><section class="integrationGrid"><article class="panel integration"><div class="letter">A</div><h3>API / Webhook</h3><p class="muted">優先方案。餐廳系統有官方 API 或 Webhook 時，QueueHub 直接接收叫號事件。</p></article><article class="panel integration"><div class="letter">B</div><h3>店家平板</h3><p class="muted">沒有 API 的店家，用這個後台 +1／跳號／暫停，仍可提供一致的前台體驗。</p></article><article class="panel integration"><div class="letter">C</div><h3>Local Gateway</h3><p class="muted">現場 edge device 對接叫號機或區網輸出，再把標準化事件送到 QueueHub。</p></article></section><section class="panel" style="padding:20px;margin-top:14px"><div class="row between"><div><h3 style="margin:0">餐廳整合設定</h3><div class="muted" style="font-size:12px">Secret 只填「伺服器端 secret 名稱」，前端不保存真正 API Key。</div></div><select class="select" onchange="pickAdmin(this.value)">${state.restaurants.map(x=>`<option value="${x.id}" ${x.id===r.id?'selected':''}>${x.name}</option>`).join('')}</select></div><div class="formGrid"><label>模式<select id="intType" class="input"><option value="api" ${c.type==='api'?'selected':''}>API</option><option value="webhook" ${c.type==='webhook'?'selected':''}>Webhook</option><option value="manual" ${c.type==='manual'?'selected':''}>Manual tablet</option><option value="gateway" ${c.type==='gateway'?'selected':''}>Local gateway</option></select></label><label style="display:flex;align-items:center;gap:8px;margin-top:22px"><input id="intEnabled" type="checkbox" ${c.enabled?'checked':''}> 啟用此整合</label><label>API Endpoint<input id="apiEndpoint" class="input" value="${esc(c.apiEndpoint)}" placeholder="https://vendor.example/api/queue"></label><label>Webhook URL<input id="webhookUrl" class="input" value="${esc(c.webhookUrl)}" placeholder="伺服器端接收網址"></label><label>Polling 秒數<input id="polling" class="input" type="number" min="1" value="${c.pollingIntervalSeconds}"></label><label>Secret 名稱<input id="secretName" class="input" value="${esc(c.apiKeySecretName)}" placeholder="QUEUE_VENDOR_API_KEY"></label><label>Gateway Device ID<input id="gatewayId" class="input" value="${esc(c.gatewayDeviceId)}" placeholder="edge-beichen-r01"></label></div><button class="btn primary" onclick="saveIntegration('${r.id}')">儲存設定</button></section><div class="notice">正式版不應讓瀏覽器直接呼叫餐廳私有 API；API Key、簽章驗證、Webhook 驗證與 vendor adapter 都應放在伺服器端。</div>`}
render=function(){const p=routeBase();if(p==='/admin'){document.getElementById('app').innerHTML=renderAdmin();nav();setTimeout(updateQrPreview,0);return}if(p==='/integrations'){document.getElementById('app').innerHTML=renderIntegrations();nav();return}coreRender()};
