window.QueueHubRuntimeConfig=Object.freeze({
  environment:'production-read',
  venueSlug:'beichen',
  venueProvider:'supabase',
  visitorProvider:'local',
  adminAuthMode:'demo',
  failOpenToLocal:true,
  supabase:{
    url:'https://goedzzhhvvnfczgnkqlv.supabase.co',
    publishableKey:'sb_publishable_6whjqbImNMa7BR9i-96M-w_dFIOFeMN'
  }
});
