let lastIssuedOrderQr=null;
function baseUrl(){return location.href.split('#')[0]}
function demoQrLink(type,r,ticket){if(type==='venue')return`${baseUrl()}#/`;if(type==='restaurant')return`${baseUrl()}#/restaurant/${r.id}`;const session=currentQueueSession(r);return`${baseUrl()}#/restaurant/${r.id}?ticket=${encodeURIComponent(ticket)}&session=${encodeURIComponent(session)}`}
function drawQr(url){const canvas=document.getElementById('qrCanvas');if(!canvas)return;if(!url){const ctx=canvas.getContext('2d');ctx?.clearRect(0,0,canvas.width,canvas.height);return}if(window.QRCode?.toCanvas)QRCode.toCanvas(canvas,url,{width:190,margin:1,errorCorrectionLevel:'M'},err=>{if(err)console.warn(err)})}
function activeIssuedQr(r,ticket){return lastIssuedOrderQr&&lastIssuedOrderQr.restaurantId===r.id&&lastIssuedOrderQr.ticketNumber===ticket&&!lastIssuedOrderQr.revoked?lastIssuedOrderQr:null}
function qrActions(liveOrder,canRevoke=false){const actions=document.querySelector('.qrDestination .actions');if(!actions)return;actions.innerHTML=liveOrder?`<button id="qrIssueBtn" class="btn primary" onclick="issueOrderQr()">產生正式 QR</button>${canRevoke?'<button id="qrRevokeBtn" class="btn warn" onclick="revokeOrderQr()">作廢目前 QR</button>':''}<button class="btn" onclick="copyQrUrl()">複製連結</button>`:'<button class="btn" onclick="copyQrUrl()">複製連結</button>'}
window.updateQrPreview=()=>{const r=getRestaurant(selectedAdmin);if(!r)return;const type=document.getElementById('qrType')?.value||'restaurant';const ticket=Number(document.getElementById('qrTicket')?.value)||168;const liveOrder=type==='order'&&QueueHubAdminGuard.isLive();const out=document.getElementById('qrUrl');const match=liveOrder?activeIssuedQr(r,ticket):null;qrActions(liveOrder,!!match?.tokenId);if(liveOrder){if(out)out.textContent=match?match.url:(lastIssuedOrderQr?.revoked&&lastIssuedOrderQr.restaurantId===r.id&&lastIssuedOrderQr.ticketNumber===ticket?'上一張正式 QR 已作廢，請產生新 QR。':'尚未產生正式 QR。按「產生正式 QR」後，token 只保留在目前畫面。');drawQr(match?.url||'');return}const url=demoQrLink(type,r,ticket);if(out)out.textContent=url;drawQr(url)};
async function revokeIssuedOrderQr(record,reason='manual revoke'){if(!record?.tokenId||record.revoked)return{ok:true,duplicate:true};const token=await QueueHubAdminAuth.ensureFresh();const c=window.QueueHubRuntimeConfig.supabase;const res=await fetch(`${String(c.url).replace(/\/$/,'')}/functions/v1/queuehub-order-qr-revoke`,{method:'POST',headers:{apikey:c.publishableKey,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({tokenId:record.tokenId,reason}),cache:'no-store'});const text=await res.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=null}if(!res.ok||!data?.ok)throw new Error(data?.detail?.message||data?.error||'正式 QR 作廢失敗');record.revoked=true;record.revokedAt=data?.result?.revoked_at||new Date().toISOString();record.url='';QueueHubDiagnostics?.count('secure_order_qr_revoked');return data}
window.revokeOrderQr=async()=>{if(!QueueHubAdminGuard.require('orderqr.revoke'))return;if(!QueueHubAdminGuard.isLive()){toast('正式 QR 作廢需要已授權的店員帳號');return}const r=getRestaurant(selectedAdmin);const ticket=Number(document.getElementById('qrTicket')?.value);const record=activeIssuedQr(r,ticket);if(!record?.tokenId){toast('目前沒有可作廢的正式 QR');return}if(!confirm(`確定作廢 ${r.name} #${ticket} 的目前 QR？作廢後已截圖或已列印的這張 QR 也會立即失效。`))return;const button=document.getElementById('qrRevokeBtn');if(button){button.disabled=true;button.textContent='作廢中…'}try{await revokeIssuedOrderQr(record,'manual staff revoke');updateQrPreview();toast('正式取餐 QR 已作廢')}catch(error){console.error(error);toast(error.message||'正式 QR 作廢失敗')}finally{if(button&&document.body.contains(button)){button.disabled=false;button.textContent='作廢目前 QR'}}};
window.issueOrderQr=async()=>{if(!QueueHubAdminGuard.require('orderqr.issue'))return;if(!QueueHubAdminGuard.isLive()){toast('正式 QR 需要已授權的店員帳號');return}const r=getRestaurant(selectedAdmin);const ticket=Number(document.getElementById('qrTicket')?.value);if(!r?.dbId){toast('目前餐廳不是正式 Supabase snapshot');return}if(!Number.isInteger(ticket)||ticket<=0){toast('請輸入有效取餐號碼');return}const button=document.getElementById('qrIssueBtn');if(button){button.disabled=true;button.textContent='產生中…'}try{const previous=activeIssuedQr(r,ticket);if(previous?.tokenId)await revokeIssuedOrderQr(previous,'reissued by staff');const token=await QueueHubAdminAuth.ensureFresh();const c=window.QueueHubRuntimeConfig.supabase;const res=await fetch(`${String(c.url).replace(/\/$/,'')}/functions/v1/queuehub-order-qr-issue`,{method:'POST',headers:{apikey:c.publishableKey,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({restaurantId:r.dbId,ticketNumber:ticket,expiresInMinutes:480}),cache:'no-store'});const text=await res.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=null}if(!res.ok||!data?.ok)throw new Error(data?.detail?.message||data?.error||'正式 QR 產生失敗');const tokenId=data?.result?.token_id||null;if(!tokenId)throw new Error('正式 QR 回應缺少 token ID，已停止顯示以避免無法作廢');lastIssuedOrderQr={restaurantId:r.id,ticketNumber:ticket,tokenId,url:data.redeemUrl,expiresAt:data.expiresAt,revoked:false};QueueHubDiagnostics?.count('secure_order_qr_issued');updateQrPreview();toast(previous?'舊 QR 已作廢並換發新 QR':'正式取餐 QR 已產生；預設 8 小時後失效')}catch(error){console.error(error);updateQrPreview();toast(error.message||'正式 QR 產生失敗')}finally{if(button&&document.body.contains(button)){button.disabled=false;button.textContent='產生正式 QR'}}};
window.copyQrUrl=async()=>{const text=document.getElementById('qrUrl')?.textContent||'';if(!/^https?:\/\//.test(text)){toast('請先產生 QR 連結');return}try{await navigator.clipboard.writeText(text);toast('QR 連結已複製')}catch(e){toast('無法存取剪貼簿')}};
